<%
dbName="test.mdb"
password="1234"

NEWflag =6 'number of days that a posting will display a ' ---NEW!' statement beside it
DAYflag = 5 'number of days after posting the date will be displayed as the day of the week

homeURL="index.asp"
forumName="Faça parte do nosso Forum!"

postsperpage=20

dim pweekday(8)
pweekday(1)="Domingo"
pweekday(2)="Segunda Feira"
pweekday(3)="Terça Feira"
pweekday(4)="Quarta Feira"
pweekday(5)="Quinta Feira"
pweekday(6)="Sexta Feira"
pweekday(7)="Sábado"
%>