<%
'#########################################################################################
'#----------------------------------------------------------------------------------------
'#########################################################################################
'#
'#  CÓDIGO: VirtuaStore Versão 1.2 - Copyright 2001-2003 VirtuaWorks                                    
'#  URL: www.virtuastore.com.br / www.virtuaworks.com.br                                                           
'#  E-MAIL: webmaster@virtuaworks.com.br                                                                                          
'#  AUTORES: Otávio Dias(Desenvolvedor) / Jone Bandinelli(Desenvolvedor) / Daniel Kern(Revisão)                
'# 
'#     Este programa é um software livre; você pode redistribuí-lo e/ou 
'#     modificá-lo sob os termos do GNU General Public License como 
'#     publicado pela Free Software Foundation.
'#     É importante lembrar que qualquer alteração feita no programa 
'#     deve ser informada e enviada para os criadores, através de e-mail 
'#     ou da página de onde foi baixado o código.
'#
'#  //-------------------------------------------------------------------------------------
'#  // LEIA COM ATENÇÃO: O software VirtuaStore 1.2 deve conter as frases
'#  // "Powered by VirtuaStore 1.2" ou "Software derivado de VirtuaStore 1.2" e 
'#  // o link para o site http://www.virtuastore.com.br no créditos da 
'#  // sua loja virtual para ser utilizado gratuitamente. Se o link e/ou uma das 
'#  // frases não estiver presentes ou visiveis este software deixará de ser
'#  // considerado Open-source(gratuito) e o uso sem autorização terá 
'#  // penalidades judiciais de acordo com as leis de pirataria de software.
'#  //--------------------------------------------------------------------------------------
'#      
'#     Este programa é distribuído com a esperança de que lhe seja útil,
'#     porém SEM NENHUMA GARANTIA. Veja a GNU General Public License
'#     abaixo (GNU Licença Pública Geral) para mais detalhes.
'# 
'#     Você deve receber a cópia da Licença GNU com este programa, 
'#     caso contrário escreva para
'#     Free Software Foundation, Inc., 59 Temple Place, Suite 330, 
'#     Boston, MA  02111-1307  USA
'# 
'#     Para enviar suas dúvidas, sugestões e/ou contratar a VirtuaWorks 
'#     Internet Design entre em contato através do e-mail 
'#     contato@virtuaworks.com.br ou pelo endereço abaixo: 
'#     Rua Venâncio Aires, 1001 - Niterói - Canoas - RS - Brasil. Cep 92110-000.
'#
'#     Para ajuda e suporte acesse: http://www.virtuastore.com.br
'#
'#     BOM PROVEITO!          
'#     Equipe VirtuaStore
'#     []'s
'#
'#########################################################################################
'#----------------------------------------------------------------------------------------
'#########################################################################################
'INÍCIO DO CÓDIGO
'----------------------------------------------------------------------------------------------------------------
'Este código está otimizado e roda tanto em Windows 2000/NT/XP/ME/98 quanto em servidores UNIX-LINUX com chilli!ASP
%>
<!-- #include file="topo.asp" -->
	 	 <SCRIPT LANGUAGE="JavaScript">
			  <!--
			  function paises(){
			  var currentState = document.registro1.outropais.checked == false; 
			  var newState = document.registro1.outropais.checked == true;
			  if (newState != currentState){
			  	 document.registro1.cepzz.disabled = newState;
				 document.registro1.estado.disabled = newState;
				 document.registro1.pais.disabled = !newState;
			 if (document.registro1.pais.disabled = !newState) {
			 	document.registro1.pais.value = "Brasil";
				}
			  }
			 }
			// -->
	  </SCRIPT>
	  		   <table><tr><td align="left" valign="top">
			   				  <table border="0" cellspacing="4" cellpadding="4" width=590><tr><td><font face="<%=fonte%>" style=font-size:11px;color:000000> <a href=default.asp style=text-decoration:none; onMouseOut="window.status='';return true;" onMouseOver="window.status='Home';return true;"><b>Home</b></a> » <%=strLg5%><br><br><div align=left> <table border=0 cellspacing=0 width=100% cellpadding=0><tr><td height=5></td></tr><tr><td height=1 bgcolor=<%=cor3%>></td></tr><tr><td height=5></td></tr></table></div><font style=font-size:10px><%=strLg122%>
							  		 <table cellspacing="1" cellpadding="1" align="center" width=98% font-style:11px><form action=registros.asp method=post name="registro1" onMouseOver="javascript: paises();"><tr><td colspan=2><br><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><b><%=strLg106%></b><table border=0 cellspacing=0 width=100% cellpadding=0><tr><td height=5></td></tr><tr><td height=1 bgcolor=<%=cor3%>></td></tr><tr><td height=5></td></tr></table></td></tr><tr><td><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><%=strLg231%></td><td><input type=text name=email style=font-family:<%=fonte%>;font-size:11px;color:#000000; size=30 value="<%=strEmail%>"></td></tr>
									 <tr><td><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><%=strLg232%></td><td><input type=password name=senha style=font-family:<%=fonte%>;font-size:11px;color:#000000; value="<%=strSenha%>"></td></tr>
									 <tr><td colspan=2><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><br><b><%=strLg107%><table border=0 cellspacing=0 width=100% cellpadding=0><tr><td height=5></td></tr><tr><td height=1 bgcolor=<%=cor3%>></td></tr><tr><td height=5></td></tr></table></b></td></tr>
									 <tr><td><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><%=strLg118%></td><td><input type=text size=40 name=nomecompleto style=font-family:<%=fonte%>;font-size:11px;color:#000000; value="<%=strNome%>"></td></tr>
									 <tr><td><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><%=strLg117%></td><td><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><select style="font-family:<%=fonte%>;font-size:11px;color:#000000;" name="nascdia">
									 <option select value="">Dia <option value="01">01<option value="02">02<option value="03">03<option value="04">04<option value="05">05<option value="06">06<option value="07">07<option value="08">08<option value="09">09<option value="10">10<option value="11">11<option value="12">12<option value="13">13<option value="14">14<option value="15">15<option value="16">16 <option value="17">17 <option value="18">18<option value="19">19<option value="20">20 <option value="21">21 <option value="22">22<option value="23">23<option value="24">24 <option value="25">25<option value="26">26<option value="27">27<option value="28">28<option value="29">29<option value="30">30 <option value="31">31</option></select> <b>/</b> <select style="font-family:<%=fonte%>;font-size:11px;color:#000000;" name="nascmes"> <option value=""> Mês <option value="Jan">Jan <option value="Fev">Fev<option value="Mar">Mar<option value="Abr">Abr<option value="Mai">Mai <option value="Jun">Jun <option value="Jul">Jul<option value="Ago">Ago<option value="Set">Set<option value="Out">Out<option value="Nov">Nov<option value="Dez">Dez</option></select> <b>/</b> <input style="font-family:<%=fonte%>;font-size:11px;color:#000000;" maxLength="4" size="5" name="nascano" value="<%=strNascano%>"></font></td></tr>
									 <tr><td><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><%=strLg116%></td><td><input type=text size=19 name=cpf style=font-family:<%=fonte%>;font-size:11px;color:#000000; value="<%=strCpf%>"></td></tr>
									 <tr><td><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><%=strLg115%></td><td><input type=text size=19 name=rg style=font-family:<%=fonte%>;font-size:11px;color:#000000; value="<%=strRg%>"></td></tr>
									 <tr><td><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><%=strLg114%></td><td><input type=text size=37 name=endereco style=font-family:<%=fonte%>;font-size:11px;color:#000000; value="<%=strEndereco%>"></td></tr>
									 <tr><td><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><%=strLg113%></td><td><input type=text size=15 name=bairro style=font-family:<%=fonte%>;font-size:11px;color:#000000; value="<%=strBairro%>"></td></tr>
									 <tr><td><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><%=strLg112%></td><td><input type=text size=34 name=cidade style=font-family:<%=fonte%>;font-size:11px;color:#000000; value="<%=strCidade%>"></td></tr>
									 <tr><td><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><%=strLg111%></td><td><select style=font-family:<%=fonte%>;font-size:11px;color:#000000; name="estado"> <option value="AC">AC<option value="AL">AL<option value="AM">AM<option value="AP">AP<option value="BA">BA<option value="CE">CE<option value="DF">DF<option value="ES">ES<option value="GO">GO<option value="MA">MA<option value="MG">MG<option value="MS">MS<option value="MT">MT<option value="PA">PA<option value="PB">PB<option value="PE">PE<option value="PI">PI<option value="PR">PR<option value="RJ">RJ<option value="RN">RN<option value="RO">RO<option value="RR">RR<option value="RS">RS<option value="SC">SC<option value="SE">SE<option value="SP">SP<option value="TO">TO</option></select><font face="<%=fonte%>" style=font-family:<%=fonte%>;font-size:11px;color:#000000;>  <input type="checkbox" name="outropais" value="Sim" onclick="javascript: paises();">Outro País</td></tr>
									 <tr><td><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><%=strLg82%></td><td><input type=text size=13 name=cepzz style=font-family:<%=fonte%>;font-size:11px;color:#000000; value="<%=strCep%>"></td></tr>
									 <tr><td><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><%=strLg110%></td><td><select style=font-family:<%=fonte%>;font-size:11px;color:#000000; name="pais">
									 <option value="Brasil">Brasil</option><option value="Afeganistão">Afeganistão</option><option value="África do Sul">África do Sul</option><option value="Aland - Finlândia">Aland - Finlândia</option><option value="Albânia">Albânia</option><option value="Alemanha">Alemanha</option><option value="Andorra">Andorra</option><option value="Angola">Angola</option><option value="Anguilla - Reino Unido">Anguilla - Reino Unido</option><option value="Antártida">Antártida</option><option value="Antígua e Barbuda">Antígua e Barbuda</option><option value="Antilhas Holandesa">Antilhas Holandesas</option><option value="Arábia Saudita">Arábia Saudita</option><option value="Argélia">Argélia</option><option value="Argentina">Argentina</option><option value="Armênia">Armênia</option><option value="Aruba - Holanda">Aruba - Holanda</option><option value="Ascensão - Reino Unido">Ascensão - Reino Unido</option><option value="Austrália">Austrália</option><option value="Áustria">Áustria</option><option value="Azerbaijão">Azerbaijão</option><option value="Bahamas">Bahamas</option><option value="Bahrein">Bahrein</option><option value="Bangladesh">Bangladesh</option><option value="Barbados">Barbados</option><option value="Belarus">Belarus</option><option value="Bélgica">Bélgica</option><option value="Belize">Belize</option><option value="Benin">Benin</option><option value="Bermudas - Reino Unido">Bermudas - Reino Unido</option><option value="Bioko - Guiné Equatorial">Bioko - Guiné Equatorial</option>
									 <option value="Bolívia">Bolívia</option><option value="Bósnia-Herzegóvina">Bósnia-Herzegóvina</option><option value="Botsuana">Botsuana</option><option value="Brunei">Brunei</option><option value="Bulgária">Bulgária</option><option value="Burkina Fasso">Burkina Fasso</option><option value="Burundi">Burundi</option><option value="Butão">Butão</option><option value="Cabo Verde">Cabo Verde</option><option value="Camarões">Camarões</option><option value="Camboja">Camboja</option><option value="Canadá">Canadá</option><option value="Cazaquistão">Cazaquistão</option><option value="Ceuta - Espanha">Ceuta - Espanha</option><option value="Chade">Chade</option><option value="Chile">Chile</option><option value="China">China</option><option value="Chipre">Chipre</option><option value="Cidade do Vaticano">Cidade do Vaticano</option><option value="Cingapura">Cingapura</option><option value="Colômbia">Colômbia</option><option value="Congo">Congo</option><option value="Coréia do Norte">Coréia do Norte</option><option value="Coréia do Sul">Coréia do Sul</option><option value="Córsega - França">Córsega - França</option><option value="Costa do Marfim">Costa do Marfim</option><option value="Costa Rica">Costa Rica</option><option value="Creta - Grécia">Creta - Grécia</option><option value="Croácia">Croácia</option><option value="Cuba">Cuba</option><option value="Curaçao - Holanda">Curaçao - Holanda</option><option value="Dinamarca">Dinamarca</option>
									 <option value="Djibuti">Djibuti</option><option value="Dominica">Dominica</option><option value="Egito">Egito</option><option value="El Salvador">El Salvador</option><option value="Emirado Árabes Unidos">Emirado Árabes Unidos</option><option value="Equador">Equador</option><option value="Eritréia">Eritréia</option><option value="Eslováquia">Eslováquia</option><option value="Eslovênia">Eslovênia</option><option value="Espanha">Espanha</option><option value="Estados Unidos">Estados Unidos</option><option value="Estônia">Estônia</option><option value="Etiópia">Etiópia</option><option value="Fiji">Fiji</option><option value="Filipinas">Filipinas</option><option value="Finlândia">Finlândia</option><option value="França">França</option><option value="Gabão">Gabão</option><option value="Gâmbia">Gâmbia</option><option value="Gana">Gana</option><option value="Geórgia">Geórgia</option><option value="Gibraltar - Reino Unido">Gibraltar - Reino Unido</option><option value="Granada">Granada</option><option value="Grécia">Grécia</option><option value="Groenlândia - Dinamarca">Groenlândia - Dinamarca</option><option value="Guadalupe - França">Guadalupe - França</option><option value="Guam - Estados Unidos">Guam - Estados Unidos</option><option value="Guatemala">Guatemala</option><option value="Guiana">Guiana</option><option value="Guiana Francesa">Guiana Francesa</option><option value="Guiné">Guiné</option><option value="Guiné Equatorial">Guiné Equatorial</option>
									 <option value="Guiné-Bissau">Guiné-Bissau</option><option value="Haiti">Haiti</option><option value="Holanda">Holanda</option><option value="Honduras">Honduras</option><option value="Hong Kong">Hong Kong</option><option value="Hungria">Hungria</option><option value="Iêmen">Iêmen</option><option value="IIhas Virgens - Estados Unidos">IIhas Virgens - Estados Unidos</option><option value="Ilha de Man - Reino Unido">Ilha de Man - Reino Unido</option><option value="Ilha Natal - Austrália">Ilha Natal - Austrália</option><option value="Ilha Norfolk - Austrália">Ilha Norfolk - Austrália</option><option value="Ilha Pitcairn - Reino Unido">Ilha Pitcairn - Reino Unido</option><option value="Ilha Wrangel - Rússia">Ilha Wrangel - Rússia</option><option value="Ilhas Aleutas - Estados Unidos">Ilhas Aleutas - Estados Unidos</option><option value="Ilhas Canárias - Espanha">Ilhas Canárias - Espanha</option><option value="Ilhas Cayman - Reino Unido">Ilhas Cayman - Reino Unido</option><option value="Ilhas Comores">Ilhas Comores</option><option value="Ilhas Cook - Nova Zelândia">Ilhas Cook - Nova Zelândia</option><option value="Ilhas do Canal - Reino Unido">Ilhas do Canal - Reino Unido</option><option value="Ilhas Salomão">Ilhas Salomão</option><option value="Ilhas Seychelles">Ilhas Seychelles</option><option value="Ilhas Tokelau - Nova Zelândia">Ilhas Tokelau - Nova Zelândia</option><option value="Ilhas Turks e Caicos - Reino Unido">Ilhas Turks e Caicos - Reino Unido</option>
									 <option value="Ilhas Virgens - Reino Unido">Ilhas Virgens - Reino Unido</option><option value="Ilhas Wallis e Futuna - França">Ilhas Wallis e Futuna - França</option><option value="Ilhsa Cocos - Austrália">Ilhsa Cocos - Austrália</option><option value="Índia">Índia</option><option value="Indonésia">Indonésia</option><option value="Irã">Irã</option><option value="Iraque">Iraque</option><option value="Irlanda">Irlanda</option><option value="Islândia">Islândia</option><option value="Israel">Israel</option><option value="Itália">Itália</option><option value="Iugoslávia">Iugoslávia</option><option value="Jamaica">Jamaica</option><option value="Jan Mayen - Noruega">Jan Mayen - Noruega</option><option value="Japão">Japão</option><option value="Jordânia">Jordânia</option><option value="Kiribati">Kiribati</option><option value="Kuait">Kuait</option><option value="Laos">Laos</option><option value="Lesoto">Lesoto</option><option value="Letônia">Letônia</option><option value="Líbano">Líbano</option><option value="Libéria">Libéria</option><option value="Líbia">Líbia</option><option value="Liechtenstein">Liechtenstein</option><option value="Lituânia">Lituânia</option><option value="Luxemburgo">Luxemburgo</option><option value="Macau - Portugal">Macau - Portugal</option><option value="Macedônia">Macedônia</option><option value="Madagascar">Madagascar</option><option value="Madeira - Portugal">Madeira - Portugal</option><option value="Malásia">Malásia</option><option value="Malaui">Malaui</option>
									 <option value="Maldivas">Maldivas</option><option value="Mali">Mali</option><option value="Malta">Malta</option><option value="Marrocos">Marrocos</option><option value="Martinica - França">Martinica - França</option><option value="Maurício - Reino Unido">Maurício - Reino Unido</option><option value="Mauritânia">Mauritânia</option><option value="México">México</option><option value="Micronésia">Micronésia</option><option value="Moçambique">Moçambique</option><option value="Moldova">Moldova</option><option value="Mônaco">Mônaco</option><option value="Mongólia">Mongólia</option><option value="MontSerrat - Reino Unido">MontSerrat - Reino Unido</option><option value="Myanma">Myanma</option><option value="Namíbia">Namíbia</option><option value="Nauru">Nauru</option><option value="Nepal">Nepal</option><option value="Nicarágua">Nicarágua</option><option value="Níger">Níger</option><option value="Nigéria">Nigéria</option><option value="Niue">Niue</option><option value="Noruega">Noruega</option><option value="Nova Bretanha - Papua-Nova Guiné">Nova Bretanha - Papua-Nova Guiné</option><option value="Nova Caledônia - França">Nova Caledônia - França</option><option value="Nova Zelândia">Nova Zelândia</option><option value="Omã">Omã</option><option value="Palau - Estados Unidos">Palau - Estados Unidos</option><option value="Palestina">Palestina</option><option value="Panamá">Panamá</option><option value="Papua-Nova Guiné">Papua-Nova Guiné</option><option value="Paquistão">Paquistão</option>
									 <option value="Paraguai">Paraguai</option><option value="Peru">Peru</option><option value="Polinésia Francesa">Polinésia Francesa</option><option value="Polônia">Polônia</option><option value="Porto Rico">Porto Rico</option><option value="Portugal">Portugal</option><option value="Qatar">Qatar</option><option value="Quênia">Quênia</option><option value="Quirguistão">Quirguistão</option><option value="Reino Unido">Reino Unido</option><option value="República Centro-Africana">República Centro-Africana</option><option value="República Dominicana">República Dominicana</option><option value="República Tcheca">República Tcheca</option><option value="Romênia">Romênia</option><option value="Ruanda">Ruanda</option><option value="Rússia">Rússia</option><option value="Samoa Ocidental">Samoa Ocidental</option><option value="San Marino">San Marino</option><option value="Santa Helena - Reino Unido">Santa Helena - Reino Unido</option><option value="Santa Lúcia">Santa Lúcia</option><option value="São Cristovão e Névis">São Cristovão e Névis</option><option value="São Tomé e Príncipe">São Tomé e Príncipe</option><option value="São Vicente e Granadinas">São Vicente e Granadinas</option><option value="Sardenha - Itália">Sardenha - Itália</option><option value="Senegal">Senegal</option><option value="Serra Leoa">Serra Leoa</option><option value="Síria">Síria</option><option value="Somália">Somália</option><option value="Sri Lanka">Sri Lanka</option><option value="Suazilândia">Suazilândia</option>
									 <option value="Sudão">Sudão</option><option value="Suécia">Suécia</option><option value="Suíça">Suíça</option><option value="Suriname">Suriname</option><option value="Tadjiquistão">Tadjiquistão</option><option value="Tailândia">Tailândia</option><option value="Taiti">Taiti</option><option value="Taiwan">Taiwan</option><option value="Tanzânia">Tanzânia</option><option value="Terra de Francisco José - Rússia">Terra de Francisco José - Rússia</option><option value="Togo">Togo</option><option value="Tonga">Tonga</option><option value="Trinidad e Tobago">Trinidad e Tobago</option><option value="Tristão da Cunha - Reino Unido">Tristão da Cunha - Reino Unido</option><option value="Tunísia">Tunísia</option><option value="Turcomenistão">Turcomenistão</option><option value="Turquia">Turquia</option><option value="Tuvalu">Tuvalu</option><option value="Ucrânia">Ucrânia</option><option value="Uganda">Uganda</option><option value="Uruguai">Uruguai</option><option value="Uzbequistão">Uzbequistão</option><option value="Vanuatu">Vanuatu</option><option value="Venezuela">Venezuela</option><option value="Vietnã">Vietnã</option><option value="Zaire">Zaire</option><option value="Zâmbia">Zâmbia</option><option value="Zimbábue">Zimbábue</option></select></td></tr>
									 <tr><td><font style=font-family:<%=fonte%>;font-size:11px;color:#000000;><%=strLg109%></td><td><input type=text size=15 name=fone style=font-family:<%=fonte%>;font-size:11px;color:#000000; value="<%=strFone%>"> <font style=font-family:<%=fonte%>;font-size:9px;color:#000000;></td></tr><tr><td colspan=2><table border=0 cellspacing=0 width=100% cellpadding=0><tr><td height=5></td></tr><tr><td height=1 bgcolor=<%=cor3%>></td></tr><tr><td height=5></td></tr></table></td></tr><tr align=center><td valign=top><div id="layer1" style="position:absolute; left:350px"><input type=image src=<%=dirlingua%>/imagens/prosseguir.gif onMouseOut="window.status='';return true;" onMouseOver="window.status='Prosseguir';return true;"></div></td><td valign=top></form><div id="layer1" style="position:absolute; left:470px"><input type=image src=<%=dirlingua%>/imagens/limpar.gif onMouseOut="window.status='';return true;" onMouseOver="window.status='Limpar';return true;" OnClick="javascript:document.registro1.reset()"></div></td></tr>
									 </table></form></td></tr>
							</table></td></tr>
			  </table>
			  <!-- #include file="baixo.asp" -->