<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD><TITLE>Grupo Vanguarda</TITLE>
<META http-equiv=Content-Type content="text/html; charset=iso-8859-1">
<LINK href="default2.css" type=text/css rel=STYLESHEET>
<!--Code generated by Cool Web Scrollbars from Harmony Hollow Software-->
<!--http://www.harmonyhollow.net-->
<STYLE type="text/css">
<!--
BODY {
scrollbar-face-color:#0080C0;
scrollbar-highlight-color:#0080C0;
scrollbar-3dlight-color:#454545;
scrollbar-darkshadow-color:#454545;
scrollbar-shadow-color:#454545;
scrollbar-arrow-color:#FFFFFF;
scrollbar-track-color:#454545;
}
-->
</STYLE>
<!--End Cool Web Scrollbars code-->

<META content="MSHTML 6.00.2600.0" name=GENERATOR></HEAD>
<BODY bgColor=#FFFFFF text="#000000" link="#000000" vlink="#000000" alink="#000000" leftMargin=0 topMargin=0 marginwidth="0" marginheight="0">
<div align="center"> 
  <p>&nbsp;</p>
  <p><img src="logo.JPG" width="102" height="114"></p>
  <p><font size="1" face="Verdana, Arial, Helvetica, sans-serif"><strong><em>Trabalhe 
    Conosco</em></strong></font></p>
  <p><font size="1" face="Verdana, Arial, Helvetica, sans-serif">Venha fazer parte 
    do Grupo Vanguarda. Seu curr&iacute;culo ser&aacute; recebido e avaliado por 
    nossa equipe de recursos humanos.<br>
    Para enviar seu curr&iacute;culo utilize o sistema. </font></p>
</div>
<form method=post ENCTYPE="multipart/form-data">
  <div align="center">
    <p> 
      <input type="file" name="File1" value="">
    </p>
    <p> 
      <input type="submit" name="Action" value="ENVIAR">
      <br>
    </p>
  </div>
</form><BR>
</BODY></HTML>
<!---#INCLUDE FILE="upload.inc" --->

<%

'Sauvegarde le fichier 'File1' sur le serveur dans le même répertoire que ce script
'Modifier le FilePath pour le claquer ailleurs
If Request.ServerVariables("REQUEST_METHOD") = "POST" Then 'Request method must be "POST" For get the fields
  Set Fields = GetUpload()
  FilePath = Server.MapPath(".") & "\" & Fields("File1").FileName
  Fields("File1").Value.SaveAs FilePath
End If

%>