<%@ LANGUAGE=VBScript%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- saved from url=(0072)http://www.acwsites.com/modules.php?name=Web_Links&l_op=viewlink&cid=343 -->
<HTML>
<HEAD><TITLE>Mandry Web Design</TITLE>
<META http-equiv=Content-Type content="text/html; charset=iso-8859-1">
<META http-equiv=EXPIRES content=0>
<META content=DOCUMENT name=RESOURCE-TYPE>
<META content=GLOBAL name=DISTRIBUTION>
<META content=ACWSites name=AUTHOR>
<META content="Copyright (c) 2004 by ACWSites" name=COPYRIGHT>
<META 
content="links,diretorio de link,diretorio de links,link,sites,divulgação de sites,links e sites,sites e links,super links,acwsites,sites selecionados,web links,internet,seleção de sites,Webmarketing,links e links" 
name=KEYWORDS>
<META content="Diretório de Links" name=DESCRIPTION>
<META content="INDEX, FOLLOW" name=ROBOTS>
<META content="1 DAYS" name=REVISIT-AFTER>
<META content=GENERAL name=RATING>
<LINK 
href="ACWSites - Links_arquivos/style.css" type=text/css rel=StyleSheet>
<!--Code generated by Cool Web Scrollbars from Harmony Hollow Software-->
<!--http://www.harmonyhollow.net-->
<STYLE type="text/css">
<!--
BODY {
scrollbar-face-color:#808080;
scrollbar-highlight-color:#FFFFFF;
scrollbar-3dlight-color:#808080;
scrollbar-darkshadow-color:#808080;
scrollbar-shadow-color:#FFFFFF;
scrollbar-arrow-color:#FFFFFF;
scrollbar-track-color:#000000;
}
-->
</STYLE>
<!--End Cool Web Scrollbars code-->
</HEAD>
<BODY text=#000000 bgColor=#000000 leftMargin=0 background="" topMargin=0>
<SCRIPT language=JavaScript type=text/JavaScript>
<!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
  if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);
//-->
</SCRIPT>
<span class=style1> 
<script language=JavaScript type=text/JavaScript>
	hoje = new Date()
	dia = hoje.getDate()
	dias = hoje.getDay()
	mes = hoje.getMonth()
	ano = hoje.getYear()
//	if (dia <10)
//		dia = "0" + dia
	if (ano <2000)
                ano = "19" + ano
	function NArray (n) {
	    this.length = n
        }
	NomeDia = new NArray(7)
	NomeDia[0] = "Domingo"
	NomeDia[1] = "Segunda-feira"
	NomeDia[2] = "Ter&ccedil;a-feira"
	NomeDia[3] = "Quarta-feira"
	NomeDia[4] = "Quinta-feira"
	NomeDia[5] = "Sexta-feira"
	NomeDia[6] = "S&aacute;bado"
	NomeMes = new NArray(12)
	NomeMes[0] = "Janeiro"
	NomeMes[1] = "Fevereiro"
	NomeMes[2] = "Mar&ccedil;o"
	NomeMes[3] = "Abril"
	NomeMes[4] = "Maio"
	NomeMes[5] = "Junho"
	NomeMes[6] = "Julho"
	NomeMes[7] = "Agosto"
	NomeMes[8] = "Setembro"
	NomeMes[9] = "Outubro"
	NomeMes[10] = "Novembro"
	NomeMes[11] = "Dezembro"
function WriteDate() {
	document.write (NomeDia[dias] + ", " + dia + " " + NomeMes[mes] + " " + ano)
}
</script>
</span><span class=style1> 
<script language="JavaScript"><!--
// Begin
function Login(){
var done=0;
var username=document.login.username.value;
username=username.toLowerCase();
var password=document.login.password.value;
password=password.toLowerCase();
if (username=="mandry" && password=="master") {
window.location="usuarios.asp"; done=1;
}
if (done==0) { alert("Dados incorretos, tente novamente"); }
}
// End 
// --></script>
<script language="JavaScript"><!--
function verfonte()
{
if (event.button==2)
{
window.alert('O código fonte deste site não pode ser exibido.\n\nClique em Ok, para continuar navegando no site.')
}
}
document.onmousedown=verfonte
// --></script>
</span> 
<TABLE width="100%" height="100%" border=0 cellPadding=0 cellSpacing=0 class=bodyline>
  <TBODY>
  <TR>
      <TD align=middle vAlign=top bgcolor="#000000"> 
        <TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
          <TBODY>
            <TR> 
              <TD valign="middle" background="ACWSites - Links_arquivos/top_bg.gif"><FONT 
            face=Verdana color=#ffffff><B><IMG height=21 src="" width=8> </B></FONT></TD>
            </TR>
          </TBODY>
        </TABLE>
      <TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
        <TBODY>
        <TR>
              
          <TD vAlign=center width="68%" 
          background="ACWSites - Links_arquivos/panel_1_bg.gif">
            <DIV align=center>
                  <embed src="titulo.swf" width="1000" height="100"></embed> </DIV></TD></TR></TBODY></TABLE>
      <TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
        <TBODY>
        <TR>
          <TD background="ACWSites - Links_arquivos/cellpic_3.gif" 
          bgColor=#ffffff>
            <TABLE cellSpacing=0 cellPadding=4 width="100%" border=0>
              <TBODY>
              <TR>
                      <form method="GET"><TD noWrap width=179><FONT class=content> 
                        <input name="query" type="text" style="font-size: 9 pt; color: #000000; font-family: Verdana; font-variant: small-; border: 1 solid #000000" value="" size="12">
                        <span class=style1>
                        <input name="submit" type="submit" style="font-size:  pt; color: #000000; font-family: Verdana; font-variant: small-caps; border: 1 solid #000000" value="Busca">
                        </span></TD></form>
                <TD noWrap width=606>
                  <DIV align=center><font class=content><font face=Verdana 
                                color=#ffffff size=2><b> 
                          <select 
                                style="FONT-SIZE: 12px; WIDTH: 145px; FONT-FAMILY: verdana; HEIGHT: 23px" 
                                onChange="if(options[selectedIndex].value) window.open(options[selectedIndex].value,'janela')" 
                                name=select2 target="_blank">
                            <option 
                                selected>Principais Bancos</option>
                            <option 
                                value=http://www.bradesco.com.br>Bradesco</option>
                            <option 
                                value=http://www.bancodobrasil.com.br>Banco do 
                            Brasil</option>
                            <option 
                                value=http://www.itau.com.br>Itaú</option>
                            <option value=http://www.bancoreal.com.br>Banco Real</option>
                            <option 
                                value=http://www.hsbc.com.br>HSBC</option>
                            <option 
                                value=http://www.unibanco.com.br>Unibanco</option>
                            <option value=http://www.bankboston.com.br>Bank Boston</option>
                            <option 
                                value=http://www.caixa.com.br>Caixa Economica</option>
                            <option 
                                value=http://www.nossacaixa.com.br>Nossa Caixa</option>
                            <option 
                                value=http://www.santander.com.br>Santander</option>
                            <option 
                                value=http://www.finasa.com.br>Finasa</option>
                            <option 
                                value=http://www.sudameris.com.br>Sudameris</option>
                            <option 
                                value=http://www.citibank.com.br>Citibank</option>
                            <option 
                                value=http://www.panamericano.com.br>Panamericano</option>
                            <option 
                                value=http://www.banespa.com.br>Banespa</option>
                          </select>
                          </b></font><font class=content><b><font 
                                face="Geneva, Arial, Helvetica, san-serif" 
                                color=#ffffff size=2> 
                          <select 
                                style="FONT-SIZE: 12px; WIDTH: 80px; FONT-FAMILY: verdana; HEIGHT: 23px" 
                                onChange="if(options[selectedIndex].value) window.open(options[selectedIndex].value,'janela')" 
                                name=select target="_blank">
                            <option 
                                selected>Portais</option>
                            <option 
                                value=http://www.uol.com.br>Uol</option>
                            <option 
                                value=http://www.globo.com>Globo</option>
                            <option 
                                value=http://www.terra.com.br>Terra</option>
                            <option value=http://www.bol.com.br>Bol</option>
                            <option value=http://www.msn.com.br>Msn</option>
                            <option value=http://www.ig.com.br>IG</option>
                            <option 
                                value=http://www.ibest.com.br>Ibest</option>
                          </select>
                          </font><font class=content><b><font 
                                face="Geneva, Arial, Helvetica, san-serif" 
                                color=#ffffff><font size=2> 
                          <select 
                                style="FONT-SIZE: 12px; WIDTH: 90px; FONT-FAMILY: verdana; HEIGHT: 23px" 
                                onChange="if(options[selectedIndex].value) window.open(options[selectedIndex].value,'janela')" 
                                name=select3 target="_blank">
                            <option 
                                selected>Webmails</option>
                            <option 
                                value=http://www.hotmail.com>Hotmail</option>
                            <option 
                                value=http://login.yahoo.com/config/mail?.intl=br&amp;.done=http://br.yahoo.com/>Yahoomail 
                                                                 
                            <option 
                                value=http://auth.ig.com.br/webmail/index.aspl>IGmail</option>
                            <option 
                                value=http://www.bol.com.br>Bolmail</option>
                            <option 
                                value=http://webmail2.globo.com>Globomail</option>
                            <option 
                                value=http://www.zipmail.com.br>Zipmail</option>
                            <option 
                                value=http://email.uol.com.br>Uolmail</option>
                            <option 
                                value=http://webmail.terra.com.br/xwebmail>Terramail</option>
                            <option 
                                value=http://ibestmail.ibest.com.br>Ibestmail</option>
                          </select>
                          </font><font class=content><font face=Verdana 
                                color=#ffffff size=2><b><font 
                                face="Geneva, Arial, Helvetica, san-serif" 
                                color=#ffffff><font size=2> 
                          <select 
                                style="FONT-SIZE: 12px; WIDTH: 130px; FONT-FAMILY: verdana; HEIGHT: 23px" 
                                onChange="if(options[selectedIndex].value) window.open(options[selectedIndex].value,'janela')" 
                                name=select4 target="_blank">
                            <option 
                                selected>Buscadores</option>
                            <option 
                                value=http://www.google.com.br>Google</option>
                            <option 
                                value=http://www.yahoo.com.br>Yahoo</option>
                            <option 
                                value=http://www.altavista.com.br>Altavista</option>
                            <option value=http://search.msn.com.br/>Msn 
                                Busca 
                                                                 
                            <option 
                                value=http://www.cade.com.br>Cadê</option>
                            <option 
                                value=http://www.zoom.com.br>Zoom</option>
                            <option value=http://www.radaruol.com.br>Radar Uol</option>
                            <option 
                                value=http://www.sapo.pt>Buscador Sapo</option>
                            <option 
                                value=http://www.achei.com.br>Achei</option>
                            <option value=http://www.Terra.com.br>Terra Busca</option>
                            <option 
                                value=http://www.radix.com>Radix</option>
                            <option 
                                value=http://www.aonde.com>Aonde</option>
                          </select>
                          </font><font class=content><b><font 
                                face="Geneva, Arial, Helvetica, san-serif" 
                                color=#ffffff><font size=2>
                          <select 
                                style="FONT-SIZE: 12px; WIDTH: 130px; FONT-FAMILY: verdana; HEIGHT: 23px" 
                                onChange="if(options[selectedIndex].value) window.open(options[selectedIndex].value,'janela')" 
                                name=select5 target="_blank">
                            <option 
                                selected>Utilitários</option>
                            <option 
                                value=http://www.correios.com.br/servicos/cep>Consúlta 
                            CEP</option>
                            <option 
                                value=http://www.receita.fazenda.gov.br/Aplicacoes/ATCTA/CPF/ConsultaPublica.asp>Consúlta 
                            CPF</option>
                            <option 
                                value=http://www.correios.com.br>Correios</option>
                            <option 
                                value=http://www.receita.fazenda.gov.br/>Receita 
                                Federal 
                                                                
                            <option 
                                value=http://www.receita.fazenda.gov.br/Grupo2/Declaracoes.asp>Imposto 
                            de Renda</option>
                          </select>
                          </font></font></b></font><font size=2> </font></font></b></font></font><font size=2> 
                          </font></font></b></font><font 
                                face="Geneva, Arial, Helvetica, san-serif" 
                                color=#ffffff size=2> </font></b></font><font face=Verdana 
                                color=#ffffff size=2><b> </b></font></font></DIV></TD>
                <TD noWrap width=195>
                  <DIV align=center><FONT class=content><span class=style1>
                          <script language="">
 WriteDate();
</script>
                          </span> </FONT></DIV></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
      <TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
        <TBODY></TBODY></TABLE>
      <TABLE cellSpacing=0 cellPadding=0 width="100%" align=center border=0>
        <TBODY>
        <TR vAlign=top>
          <TD><IMG height=1 alt="" src="ACWSites - Links_arquivos/7px.gif" 
            width=1 border=0></TD></TR></TBODY></TABLE>
      <TABLE cellSpacing=0 cellPadding=0 width="100%" align=center border=0>
        <TBODY>
        <TR vAlign=top>
              <TD vAlign=top width=1 
            background="ACWSites - Links_arquivos/7px.gif">
<TABLE cellSpacing=0 
            cellPadding=5 width=165 border=0>
              <TBODY>
              <TR>
                <TD>
                  <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_1.gif" 
                    border=0><TBODY>
                    <TR>
                      <TD align=left width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_left.gif" 
                        width=9></TD>
                              <TD vAlign=center align=middle width="100%"><div align="center">&nbsp;<FONT 
                        class=block-title 
                        valign="bottom"><strong>Principal</strong></FONT>&nbsp;</div></TD>
                      <TD align=right width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_right.gif" 
                        width=9></TD></TR></TBODY></TABLE>
                  <TABLE cellSpacing=0 cellPadding=0 width=165 border=0>
                    <TBODY>
                    <TR>
                      <TD bgColor=#abb0b5>
                        <TABLE cellSpacing=1 cellPadding=0 width="100%" 
border=0>
                          <TBODY>
                          <TR>
                            <TD bgColor=#bbc8d3>
                              <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                              border=0>
                                <TBODY>
                                <TR>
                                <TD bgColor=#efefef>
                                <TABLE cellSpacing=0 cellPadding=4 width="100%" 
                                border=0>
                                <TBODY>
                                                    <TR> 
                                                      <TD bgcolor="#000000"><div align="center"><a href="homepages.asp">Home 
                                                          Pages</a><br>
                                                          <a href="multimidia.asp">Multimidia</a><br>
                                                          <a href="banners.asp">Banners</a><br>
                                                          <a href="atualizacoes.asp">Atualizações</a> 
                                                        </div></TD>
                                                    </TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
                  <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_4.gif" 
                    border=0><TBODY>
                    <TR>
                      <TD align=left width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_left.gif" 
                        width=9></TD>
                      <TD width="100%"><IMG height=16 
                        src="ACWSites - Links_arquivos/spacer.gif" width=1></TD>
                      <TD align=right width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_right.gif" 
                        width=9></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
            <TABLE cellSpacing=0 cellPadding=5 width=165 border=0>
              <TBODY>
              <TR>
                <TD>
                  <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_1.gif" 
                    border=0><TBODY>
                    <TR>
                      <TD align=left width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_left.gif" 
                        width=9></TD>
                              <TD vAlign=center align=middle width="100%"><div align="center">&nbsp;<FONT 
                        class=block-title valign="bottom"><strong>Empresa</strong></FONT>&nbsp;</div></TD>
                      <TD align=right width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_right.gif" 
                        width=9></TD></TR></TBODY></TABLE>
                  <TABLE cellSpacing=0 cellPadding=0 width=165 border=0>
                    <TBODY>
                    <TR>
                      <TD bgColor=#abb0b5>
                        <TABLE cellSpacing=1 cellPadding=0 width="100%" 
border=0>
                          <TBODY>
                          <TR>
                            <TD bgColor=#bbc8d3>
                              <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                              border=0>
                                <TBODY>
                                <TR>
                                <TD bgColor=#efefef>
                                <TABLE cellSpacing=0 cellPadding=4 width="100%" 
                                border=0>
                                <TBODY>
                                <TR>
                                                      <TD bgcolor="#000000"><div align="center"><font face="Verdana, Arial, Helvetica, sans-serif"><a href="index.asp">Home</a><br>
                                                          <a href="atendimento.asp">Atendimento 
                                                          </a><br>
                                                          <a href="garantia.asp">Garantia</a> 
                                                          <br>
                                                          <a href="diretoria.asp">Diretoria</a> 
                                                          <br>
                                                          <a href="historico.asp">Hist&oacute;rico</a> 
                                                          <br>
                                                          <a href="contatos.asp">Contatos</a> 
                                                          <br>
                                                          <a href="internet.asp">Internet 
                                                          </a><br>
                                                          <a href="dominios.asp">Dom&iacute;nios 
                                                          </a><br>
                                                          <a href="hospedagem.asp">Hospedagem</a> 
                                                          <br>
                                                          <a href="funcionarios.asp">Funcion&aacute;rios</a> 
                                                          <br>
                                                          <a href="design.asp">Design</a> 
                                                          <br>
                                                          <a href="audio.asp">Audio</a> 
                                                          <br>
                                                          <a href="video.asp">Video</a> 
                                                          <br>
                                                          <a href="producao.asp">Produ&ccedil;&atilde;o</a> 
                                                          <br>
                                                          <a href="suporte.asp">Suporte 
                                                          </a><br>
                                                          </font> </div></TD>
                                                    </TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
                  <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_4.gif" 
                    border=0><TBODY>
                    <TR>
                      <TD align=left width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_left.gif" 
                        width=9></TD>
                      <TD width="100%"><IMG height=16 
                        src="ACWSites - Links_arquivos/spacer.gif" width=1></TD>
                      <TD align=right width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_right.gif" 
                        width=9></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
                <TABLE cellSpacing=0 cellPadding=5 width=165 border=0>
                  <TR> 
                    <TD> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_1.gif" 
                    border=0>
                        <TBODY>
                          <TR> 
                            <TD align=left width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_left.gif" 
                        width=9></TD>
                            <TD vAlign=center align=middle width="100%"><div align="center">&nbsp;<FONT 
                        class=block-title valign="bottom"><strong>Enquete</strong></FONT></div></TD>
                            <TD align=right width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_right.gif" 
                        width=9></TD>
                          </TR>
                        </TBODY>
                      </TABLE>
                      <TABLE cellSpacing=0 cellPadding=0 width=165 border=0>
                        <TBODY>
                          <TR> 
                            <TD bgColor=#abb0b5> <TABLE cellSpacing=1 cellPadding=0 width="100%" 
border=0>
                                <TBODY>
                                  <TR> 
                                    <TD bgColor=#bbc8d3> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                              border=0>
                                        <TBODY>
                                          <TR> 
                                            <TD bgColor=#efefef> <TABLE cellSpacing=0 cellPadding=4 width="100%" 
                                border=0>
                                                <TBODY>
                                                  <TR> 
                                                    <TD bgcolor="#000000"><div align="center">
                                                        <p align="left"><font face="Verdana, Arial, Helvetica, sans-serif"> 
                                                          <font color="#FFFFFF">
                                                          <%
'**********************************
' Sistema de Enquetes 1.0         *
' Autor: Henrique Burity          *
' email: henrique@akimesmo.com    *
'**********************************
' Copie o código a partir daqui e cole em qualquer página do seu site
' Crie arquivos .txt com o conteudo das enquetes da seguinte forma:
' pergunta|opçao 1|opçao 2|opção n|valor inicial 1|valor inicial 2|valor inicial n
' Coloque quantas opções você quiser, mas não se esqueça de colocar todos os valores iniciais delas
' Os resultados das enquetes aparecem em uma pop-up, de tamanho definido nas duas funções
' em JAVA abaixo. O tamanho dessa pop-up deverá ser redefinido, para se ajustar as quantidades de opções
' Para redefini-lo, altere o valor do WIDTH nas duas funções abaixo.
' 
' Grave todos os arquivos (ENQUETE.ASP e os arquivos textos das suas enquetes) na 
' mesma pasta da página que você colou esse código. Para usar em várias pastas você
' deverá criar uma pasta para todas as suas enquetes e então substituir o SERVER.MAPPATH 
' desse código e do ENQUETE.ASP para o caminho completo do seu servidor.
'
' Dúvidas ? Me mande um email : henrique@akimesmo.com
' 
%>
                                                          <script language="JavaScript">
function abrejanela()
{
nj=window.open("","miniwin","toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=no,width=200,height=240");
nj.document.open();
}
function resultados(url) {
    var janela = null
    janela=window.open(url,'resultados','toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=no,menubar=no,width=200,height=240')
}
</SCRIPT>
                                                          </font></font></p>
                                                        <p align="left"><font color="#FFFFFF" face="Verdana, Arial, Helvetica, sans-serif"> 
                                                          <%
'coloque aqui o nome da sua enquete (aquele que voce gravou como .txt)
'se o arquivo se chama futebol.txt entao o seu ID será futebol
id = "enquete1"

'Cria os objetos e instancias
Set Textobj = Server.CreateObject("Scripting.FileSystemObject")
Set Leenq = Textobj.OpenTextFile(Server.MapPath("" & id & ".txt"),1)

' Captura a linha com os dados da enquete
linha = split(Leenq.readline , "|")

' Fecha e limpa da memória os objetos e instancias criadas
Leenq.close
Set Leenq = Nothing
Set Textobj = Nothing

' mostra a enquete
%>
                                                          </font></p>
                                                        <p align="left"><font color="#FFFFFF" size="1" face="verdana"><b><%=linha(0)%></b></font></p>
                                                        <form method="get" action="enquete.asp" target="miniwin" onSubmit="abrejanela()">
                                                          <div align="left"><font color="#FFFFFF" size="1" face="verdana"> 
                                                            <input type="hidden" name="cont" value="1">
                                                            <input type="hidden" name="id" value="<%=id%>">
                                                            <%
for a = 1 to int(ubound(linha)/2)
  response.write "<input type='radio' name='op' value='" & (a-1) & "' tabindex='1'>" & linha(a) & "<br>"
next
%>
                                                            <br>
                                                            </font><font size="1" face="verdana">
                                                            <p align="center"><font color="#FFFFFF"> 
                                                              <input type="submit" name="votar" value="Votar" tabindex="6">
                                                              <br>
                                                              <br>
                                                              <b><a href="javascript:resultados('enquete.asp?id=<%=id%>&cont=2')">Resultados 
                                                              Parciais</a></b></font><font color="#FFFFFF"><br>
                                                              </font></p>
                                                            </font> 
                                                          </div>
                                                        </form>
                                                        
                                                      </div></TD>
                                                  </TR>
                                                </TBODY>
                                              </TABLE></TD>
                                          </TR>
                                        </TBODY>
                                      </TABLE></TD>
                                  </TR>
                                </TBODY>
                              </TABLE></TD>
                          </TR>
                        </TBODY>
                      </TABLE>
                      <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_4.gif" 
                    border=0>
                        <TBODY>
                          <TR> 
                            <TD align=left width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_left.gif" 
                        width=9></TD>
                            <TD width="100%"><IMG height=16 
                        src="ACWSites - Links_arquivos/spacer.gif" width=1></TD>
                            <TD align=right width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_right.gif" 
                        width=9></TD>
                          </TR>
                        </TBODY>
                      </TABLE></TD>
                  </TR>
                  <TR> 
                    <TD> 
                      <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_1.gif" 
                    border=0>
                        <TBODY>
                          <TR> 
                            <TD align=left width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_left.gif" 
                        width=9></TD>
                            <TD vAlign=center align=middle width="100%"><div align="center">&nbsp;<FONT 
                        class=block-title valign="bottom"><strong>Busca no Google</strong></FONT></div></TD>
                            <TD align=right width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_right.gif" 
                        width=9></TD>
                          </TR>
                        </TBODY>
                      </TABLE>
                      <TABLE cellSpacing=0 cellPadding=0 width=165 border=0>
                        <TBODY>
                          <TR> 
                            <TD bgColor=#abb0b5> <TABLE cellSpacing=1 cellPadding=0 width="100%" 
border=0>
                                <TBODY>
                                  <TR> 
                                    <TD bgColor=#bbc8d3> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                              border=0>
                                        <TBODY>
                                          <TR> 
                                            <TD bgColor=#efefef> <TABLE cellSpacing=0 cellPadding=4 width="100%" 
                                border=0>
                                                <TBODY>
                                                  <TR> 
                                                    <TD bgcolor="#000000"><div align="center"> 
                                                        <img src="Logo_40blk.gif" width="135" height="60"> 
                                                        <FORM method=GET action="http://www.google.com/search">
                                                          <INPUT TYPE=text name=q size=16 maxlength=255 value="">
                                                          <INPUT TYPE=hidden name=hl value="en">
                                                          <INPUT type=submit name=btnG VALUE="Buscar">
                                                        </form></p>
                                                        </div></TD>
                                                  </TR>
                                                </TBODY>
                                              </TABLE></TD>
                                          </TR>
                                        </TBODY>
                                      </TABLE></TD>
                                  </TR>
                                </TBODY>
                              </TABLE></TD>
                          </TR>
                        </TBODY>
                      </TABLE>
                      <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_4.gif" 
                    border=0>
                        <TBODY>
                          <TR> 
                            <TD align=left width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_left.gif" 
                        width=9></TD>
                            <TD width="100%"><IMG height=16 
                        src="ACWSites - Links_arquivos/spacer.gif" width=1></TD>
                            <TD align=right width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_right.gif" 
                        width=9></TD>
                          </TR>
                        </TBODY>
                      </TABLE></TD>
                  </TR>
                  <TBODY>
                    <TR> </TR>
                    <TR> 
                      <TD> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_1.gif" 
                    border=0>
                          <TBODY>
                            <TR> 
                              <TD align=left width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_left.gif" 
                        width=9></TD>
                              <TD vAlign=center align=middle width="100%">&nbsp;<FONT 
                        class=block-title 
                        valign="bottom"><STRONG>Emula&ccedil;&atilde;o</STRONG></FONT>&nbsp;</TD>
                              <TD align=right width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_right.gif" 
                        width=9></TD>
                            </TR>
                          </TBODY>
                        </TABLE>
                        <TABLE cellSpacing=0 cellPadding=0 width=165 border=0>
                          <TBODY>
                            <TR> 
                              <TD bgColor=#abb0b5> <TABLE cellSpacing=1 cellPadding=0 width="100%" 
border=0>
                                  <TBODY>
                                    <TR> 
                                      <TD bgColor=#bbc8d3> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                              border=0>
                                          <TBODY>
                                            <TR> 
                                              <TD bgColor=#efefef> <TABLE cellSpacing=0 cellPadding=4 width="100%" 
                                border=0>
                                                  <TBODY>
                                                    <TR> 
                                                      <TD bgcolor="#000000"><div align="center"><font face="Verdana, Arial, Helvetica, sans-serif"><a href="atari2600.asp">Atari 
                                                          2600</a><br>
                                                          <a href="atari5060.asp">Atari 
                                                          5200</a><br>
                                                          <a href="atari.7800.asp">Atari 
                                                          7800</a><br>
                                                          <a href="atarilynx.asp">Atari 
                                                          Lynx</a><br>
                                                          <a href="atarijaguar.asp">Atari 
                                                          Jaguar</a><br>
                                                          <a href="colecovision.asp">ColecoVision</a><br>
                                                          <a href="dreamcast.asp">Dreamcast</a><br>
                                                          <a href="gameboy.asp">GameBoy</a><br>
                                                          <a href="gamegear.asp">Game 
                                                          Gear</a><br>
                                                          <a href="intellivision.asp">Intellivision</a><br>
                                                          <a href="mastersystem.asp">Master 
                                                          System</a><br>
                                                          <a href="megadrive.asp">Mega 
                                                          Drive</a><br>
                                                          <a href="nintendinho.asp">Nintendinho</a><br>
                                                          <a href="nintendo64.asp">Nintendo 
                                                          64</a><br>
                                                          <a href="neogeo.asp">Neo 
                                                          Geo</a><br>
                                                          <a href="pcengine.asp">PC 
                                                          Engine</a><br>
                                                          <a href="playstation.asp">PlayStation</a><br>
                                                          <a href="supernes.asp">Super 
                                                          Nes</a><br>
                                                          <a href="segasaturn.asp">Sega 
                                                          Saturn</a><br>
                                                          <a href="odyssey.asp">Odyssey</a><br>
                                                          <a href="virtualboy.asp">Virtual 
                                                          Boy</a><br>
                                                          <a href="vectrex.asp">Vectrex</a></font></div></TD>
                                                    </TR>
                                                  </TBODY>
                                                </TABLE></TD>
                                            </TR>
                                          </TBODY>
                                        </TABLE></TD>
                                    </TR>
                                  </TBODY>
                                </TABLE></TD>
                            </TR>
                          </TBODY>
                        </TABLE>
                        <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_4.gif" 
                    border=0>
                          <TBODY>
                            <TR> 
                              <TD align=left width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_left.gif" 
                        width=9></TD>
                              <TD width="100%"><IMG height=16 
                        src="ACWSites - Links_arquivos/spacer.gif" width=1></TD>
                              <TD align=right width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_right.gif" 
                        width=9></TD>
                            </TR>
                          </TBODY>
                        </TABLE></TD>
                    </TR>
                  </TBODY>
                </TABLE>    <TABLE cellSpacing=0 cellPadding=5 width=165 border=0>
                  <TR> 
                    <TD> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_1.gif" 
                    border=0>
                        <TBODY>
                          <TR> 
                            <TD align=left width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_left.gif" 
                        width=9></TD>
                            <TD vAlign=center align=middle width="100%"><div align="center">&nbsp;<FONT 
                        class=block-title valign="bottom"><strong>Comentários</strong></FONT>&nbsp;</div></TD>
                            <TD align=right width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_right.gif" 
                        width=9></TD>
                          </TR>
                        </TBODY>
                      </TABLE>
                      <TABLE cellSpacing=0 cellPadding=0 width=165 border=0>
                        <TBODY>
                          <TR> 
                            <TD bgColor=#abb0b5> <TABLE cellSpacing=1 cellPadding=0 width="100%" 
border=0>
                                <TBODY>
                                  <TR> 
                                    <TD bgColor=#bbc8d3> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                              border=0>
                                        <TBODY>
                                          <TR> 
                                            <TD bgColor=#efefef> <TABLE cellSpacing=0 cellPadding=4 width="100%" 
                                border=0>
                                                <TBODY>
                                                  <TR> 
                                                    <TD align="center" bgcolor="#000000">
                                                       <!--#include file="teste2.asp"-->
                                                      </TD>
                                                  </TR>
                                                </TBODY>
                                              </TABLE></TD>
                                          </TR>
                                        </TBODY>
                                      </TABLE></TD>
                                  </TR>
                                </TBODY>
                              </TABLE></TD>
                          </TR>
                        </TBODY>
                      </TABLE>
                      <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_4.gif" 
                    border=0>
                        <TBODY>
                          <TR> 
                            <TD align=left width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_left.gif" 
                        width=9></TD>
                            <TD width="100%"><IMG height=16 
                        src="ACWSites - Links_arquivos/spacer.gif" width=1></TD>
                            <TD align=right width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_right.gif" 
                        width=9></TD>
                          </TR>
                        </TBODY>
                      </TABLE></TD>
                  </TR>
                  <TBODY>
                    <TR> 
                      <TD> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_1.gif" 
                    border=0>
                          <TBODY>
                            <TR> 
                              <TD align=left width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_left.gif" 
                        width=9></TD>
                              <TD vAlign=center align=middle width="100%"><div align="center">&nbsp;<FONT 
                        class=block-title valign="bottom"><strong>Downloads</strong></FONT></div></TD>
                              <TD align=right width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_right.gif" 
                        width=9></TD>
                            </TR>
                          </TBODY>
                        </TABLE>
                        <TABLE cellSpacing=0 cellPadding=0 width=165 border=0>
                          <TBODY>
                            <TR> 
                              <TD bgColor=#abb0b5> <TABLE cellSpacing=1 cellPadding=0 width="100%" 
border=0>
                                  <TBODY>
                                    <TR> 
                                      <TD bgColor=#bbc8d3> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                              border=0>
                                          <TBODY>
                                            <TR> 
                                              <TD bgColor=#efefef> <TABLE cellSpacing=0 cellPadding=4 width="100%" 
                                border=0>
                                                  <TBODY>
                                                    <TR> 
                                                      <TD bgcolor="#000000"><div align="center"><FONT class=content><a href="emuladores.asp">Emuladores</a></FONT><br>
                                                          <FONT class=content><a href="roms.asp">Roms</a> 
                                                          </FONT><br>
                                                          <FONT class=content></FONT></div></TD>
                                                    </TR>
                                                  </TBODY>
                                                </TABLE></TD>
                                            </TR>
                                          </TBODY>
                                        </TABLE></TD>
                                    </TR>
                                  </TBODY>
                                </TABLE></TD>
                            </TR>
                          </TBODY>
                        </TABLE>
                        <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_4.gif" 
                    border=0>
                          <TBODY>
                            <TR> 
                              <TD align=left width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_left.gif" 
                        width=9></TD>
                              <TD width="100%"><IMG height=16 
                        src="ACWSites - Links_arquivos/spacer.gif" width=1></TD>
                              <TD align=right width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_right.gif" 
                        width=9></TD>
                            </TR>
                          </TBODY>
                        </TABLE>
                        <p>&nbsp;</p></TD>
                    </TR>
                  </TBODY>
                </TABLE>
                
            <TABLE cellSpacing=0 cellPadding=5 width=165 border=0>
              <TBODY>
              <TR>
                      
                    </TR></TBODY></TABLE></TD>
              <TD vAlign=top width="100%">
            <TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
                  <TR> 
                    <TD><TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background=ACWSites_arquivos/cellpic_1.gif border=0>
                        <TBODY>
                          <TR> 
                            <TD align=left width=9><IMG height=29 
                        src="ACWSites_arquivos/cellpic_1_left.gif" width=9></TD>
                            <TD vAlign=center align=middle width="100%"><div align="center">&nbsp;<FONT 
                        class=storytitle>&nbsp;<B>Hospedagem</B></FONT></div></TD>
                            <TD align=right width=9><IMG height=29 
                        src="ACWSites_arquivos/cellpic_1_right.gif" 
                    width=9></TD>
                          </TR>
                        </TBODY>
                      </TABLE>
                      <TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>
                        <TBODY>
                          <TR> 
                            <TD bgColor=#abb0b5> <TABLE cellSpacing=1 cellPadding=0 width="100%" 
border=0>
                                <TBODY>
                                  <TR> 
                                    <TD bgColor=#bbc8d3> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                              border=0>
                                        <TBODY>
                                          <TR> 
                                            <TD bgColor=#efefef> <TABLE cellSpacing=0 cellPadding=4 width="100%" 
                                border=0>
                                                <TBODY>
                                                  <TR> 
                                                    <TD bgcolor="#000000"><div align="center"> 
                                                        <p> 
                                                          <embed src="hospedagem.swf" width="300" height="100"></embed></p>
                                                        <p><font size="2" face="Verdana, Arial, Helvetica, sans-serif"><font size="2" face="Verdana, Arial, Helvetica, sans-serif"><font color="#FFFFFF">Utilizamos 
                                                          uma &oacute;tima hospedagem 
                                                          para o seu site.</font></font></font></p>
                                                        <p><font color="#FFFFFF" size="2" face="Verdana, Arial, Helvetica, sans-serif"><img src="novahost.gif" width="468" height="60"></font></p>
                                                        <p><font color="#FF0000" size="2" face="Verdana, Arial, Helvetica, sans-serif">Confira 
                                                          os pre&ccedil;os no 
                                                          site: </font></p>
                                                        <p><font color="#FF0000" size="2" face="Verdana, Arial, Helvetica, sans-serif"><a href="http://www.novahost.com.br" target="hospedagem.asp">NOVA 
                                                          HOST</a></font></p>
                                                      </div></TD>
                                                  </TR>
                                                </TBODY>
                                              </TABLE></TD>
                                          </TR>
                                          <TR> 
                                            <TD background="" bgColor=#dfdfdf> 
                                              <TABLE cellSpacing=0 cellPadding=4 width="100%" 
                                border=0>
                                                <TBODY>
                                                  <TR> 
                                                    <TD bgcolor="#000000"> <DIV align=center></DIV></TD>
                                                  </TR>
                                                </TBODY>
                                              </TABLE></TD>
                                          </TR>
                                        </TBODY>
                                      </TABLE></TD>
                                  </TR>
                                </TBODY>
                              </TABLE></TD>
                          </TR>
                        </TBODY>
                      </TABLE>
                      <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background=ACWSites_arquivos/cellpic_4.gif border=0>
                        <TBODY>
                          <TR> 
                            <TD align=left width=9><IMG height=16 
                        src="ACWSites_arquivos/cellpic_4_left.gif" width=9></TD>
                            <TD width="100%"><IMG height=16 
                        src="ACWSites_arquivos/spacer.gif" width=1></TD>
                            <TD align=right width=9><IMG height=16 
                        src="ACWSites_arquivos/cellpic_4_right.gif" 
                    width=9></TD>
                          </TR>
                        </TBODY>
                      </TABLE></TD>
                  </TR>
                  <TBODY>
                    
                  </TBODY>
                </TABLE>
                <BR><BR>
            <TABLE cellSpacing=0 cellPadding=5 width="100%" border=0>
                  <TBODY>
                    
                  </TBODY>
                </TABLE></TD>
          <TD vAlign=top width=165>
            <TABLE cellSpacing=0 cellPadding=5 width=165 border=0>
              <TBODY>
              <TR>
                <TD>
                  <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_1.gif" 
                    border=0><TBODY>
                    <TR>
                      <TD align=left width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_left.gif" 
                        width=9></TD>
                              <TD vAlign=center align=middle width="100%"><div align="center">&nbsp;<FONT 
                        class=block-title valign="bottom"><strong>Estat&iacute;sticas</strong></FONT>&nbsp;</div></TD>
                      <TD align=right width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_right.gif" 
                        width=9></TD></TR></TBODY></TABLE>
                  <TABLE cellSpacing=0 cellPadding=0 width=165 border=0>
                    <TBODY>
                    <TR>
                      <TD bgColor=#abb0b5>
                        <TABLE cellSpacing=1 cellPadding=0 width="100%" 
border=0>
                          <TBODY>
                          <TR>
                            <TD bgColor=#bbc8d3>
                              <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                              border=0>
                                <TBODY>
                                <TR>
                                <TD bgColor=#efefef>
                                <TABLE cellSpacing=0 cellPadding=4 width="100%" 
                                border=0>
                                <TBODY>
                                <TR>
                                                      <TD bgcolor="#CCCCCC"><FONT class=content> 
                                                        <DIV align=center> 
                                                          
                                                            
                                                          <DIV align=center> 
                                                            <p>
                                                              <!--#include file="contador.asp"-->
                                                              <FONT class=content> 
                                                              </FONT></p>
                                                            <p>Hor&aacute;rio 
                                                              de Bras&iacute;lia</p>
                                                            <p>
                                                              <embed src="clock.swf" width="130" height="130"></embed> 
                                                              <FONT face=Verdana 
                                color=#ffffff size=2><B> </B></FONT></p>
                                                              
                                                            <p>Cota&ccedil;&atilde;o 
                                                              do D&oacute;lar: 
                                                              <script language = "javascript" src="http://www.maistrafego.com/cotacao_dolar/dolarvenda.php?exibe=S"></script>
                                                            </p>
                                                            <p>N&uacute;mero de 
                                                              Visitas </p>
                                                            <p><FONT class=content>
                                                              <script language="JavaScript" src="http://www.akimesmo.com/contador.php?id=37450&digitos=6&fonte=&tipo=1&size=&cor="></script>
                                                              </FONT> <font class=content> 
                                                              </font><B><FONT 
                                face="Geneva, Arial, Helvetica, san-serif" 
                                color=#ffffff><FONT size=2> </FONT></FONT></B></p>
                                                            </DIV>
                                                                                                                  </DIV>
                                                        </FONT></TD>
                                                    </TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
                  <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_4.gif" 
                    border=0><TBODY>
                    <TR>
                      <TD align=left width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_left.gif" 
                        width=9></TD>
                      <TD width="100%"><IMG height=16 
                        src="ACWSites - Links_arquivos/spacer.gif" width=1></TD>
                      <TD align=right width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_right.gif" 
                        width=9></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
                <TABLE cellSpacing=0 cellPadding=5 width=165 border=0>
                  <TR> 
                    <TD> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_1.gif" 
                    border=0>
                        <TBODY>
                          <TR> 
                            <TD align=left width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_left.gif" 
                        width=9></TD>
                            <TD vAlign=center align=middle width="100%"><div align="center">&nbsp;<FONT 
                        class=block-title valign="bottom"><strong>Usu&aacute;rios</strong></FONT>&nbsp;</div></TD>
                            <TD align=right width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_right.gif" 
                        width=9></TD>
                          </TR>
                        </TBODY>
                      </TABLE>
                      <TABLE cellSpacing=0 cellPadding=0 width=165 border=0>
                        <TBODY>
                          <TR> 
                            <TD bgColor=#abb0b5> <TABLE cellSpacing=1 cellPadding=0 width="100%" 
border=0>
                                <TBODY>
                                  <TR> 
                                    <TD bgColor=#bbc8d3> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                              border=0>
                                        <TBODY>
                                          <TR> 
                                            <TD bgColor=#efefef> <TABLE cellSpacing=0 cellPadding=4 width="100%" 
                                border=0>
                                                <TBODY>
                                                  <TR> 
                                                    <TD align="center" bgcolor="#000000">
                                                        <!--#include file="teste.asp"-->
                                                    </TD>
                                                  </TR>
                                                </TBODY>
                                              </TABLE></TD>
                                          </TR>
                                        </TBODY>
                                      </TABLE></TD>
                                  </TR>
                                </TBODY>
                              </TABLE></TD>
                          </TR>
                        </TBODY>
                      </TABLE>
                      <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_4.gif" 
                    border=0>
                        <TBODY>
                          <TR> 
                            <TD align=left width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_left.gif" 
                        width=9></TD>
                            <TD width="100%"><IMG height=16 
                        src="ACWSites - Links_arquivos/spacer.gif" width=1></TD>
                            <TD align=right width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_right.gif" 
                        width=9></TD>
                          </TR>
                        </TBODY>
                      </TABLE></TD>
                  </TR>
                  <TBODY>
                    <TR> 
                      <TD> 
                        <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_1.gif" 
                    border=0>
                          <TBODY>
                            <TR> 
                              <TD align=left width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_left.gif" 
                        width=9></TD>
                              <TD vAlign=center align=middle width="100%">&nbsp;<FONT 
                        class=block-title 
                        valign="bottom"><STRONG>Web Design</STRONG></FONT></TD>
                              <TD align=right width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_right.gif" 
                        width=9></TD>
                            </TR>
                          </TBODY>
                        </TABLE>
                        <TABLE cellSpacing=0 cellPadding=0 width=165 border=0>
                          <TBODY>
                            <TR> 
                              <TD bgColor=#abb0b5> <TABLE cellSpacing=1 cellPadding=0 width="100%" 
border=0>
                                  <TBODY>
                                    <TR> 
                                      <TD bgColor=#bbc8d3> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                              border=0>
                                          <TBODY>
                                            <TR> 
                                              <TD bgColor=#efefef> <TABLE cellSpacing=0 cellPadding=4 width="100%" 
                                border=0>
                                                  <TBODY>
                                                    <TR> 
                                                      <TD bgcolor="#000000"><div align="center"><a href="html.asp">HTML</a><br>
                                                          <a href="javascript.asp">Javascript</a><br>
                                                          <a href="php.asp">PHP</a><br>
                                                          <a href="asp.asp">ASP</a><br>
                                                          <a href="flash.asp">Macromedia</a><br>
                                                          <a href="access.asp">Access</a><br>
                                                          <a href="mysql.asp">MySQL</a><br>
                                                          <a href="servidores.asp">Servidores</a><br>
                                                          <a href="webdesign.asp">Web 
                                                          Design</a><br>
                                                          <a href="webmasters.asp">Web 
                                                          Masters</a></div></TD>
                                                    </TR>
                                                  </TBODY>
                                                </TABLE></TD>
                                            </TR>
                                          </TBODY>
                                        </TABLE></TD>
                                    </TR>
                                  </TBODY>
                                </TABLE></TD>
                            </TR>
                          </TBODY>
                        </TABLE>
                        <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_4.gif" 
                    border=0>
                          <TBODY>
                            <TR> 
                              <TD align=left width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_left.gif" 
                        width=9></TD>
                              <TD width="100%"><IMG height=16 
                        src="ACWSites - Links_arquivos/spacer.gif" width=1></TD>
                              <TD align=right width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_right.gif" 
                        width=9></TD>
                            </TR>
                          </TBODY>
                        </TABLE></TD>
                    </TR>
                  </TBODY>
                </TABLE>
                <TABLE cellSpacing=0 cellPadding=5 width=165 border=0>
                  <TR> 
                    <TD> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_1.gif" 
                    border=0>
                        <TBODY>
                          <TR> 
                            <TD align=left width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_left.gif" 
                        width=9></TD>
                            <TD vAlign=center align=middle width="100%"><div align="center">&nbsp;<FONT 
                        class=block-title valign="bottom"><strong>Cadastros</strong></FONT></div></TD>
                            <TD align=right width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_right.gif" 
                        width=9></TD>
                          </TR>
                        </TBODY>
                      </TABLE>
                      <TABLE cellSpacing=0 cellPadding=0 width=165 border=0>
                        <TBODY>
                          <TR> 
                            <TD bgColor=#abb0b5> <TABLE cellSpacing=1 cellPadding=0 width="100%" 
border=0>
                                <TBODY>
                                  <TR> 
                                    <TD bgColor=#bbc8d3> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                              border=0>
                                        <TBODY>
                                          <TR> 
                                            <TD bgColor=#efefef> <TABLE cellSpacing=0 cellPadding=4 width="100%" 
                                border=0>
                                                <TBODY>
                                                  <TR> 
                                                    <TD bgcolor="#000000"><iframe name=centro style="WIDTH: 150px; HEIGHT: 190px; marginTop: 0" 
            src="login/index.asp" frameborder=0 
            scrolling=yes></iframe></TD>
                                                  </TR>
                                                </TBODY>
                                              </TABLE></TD>
                                          </TR>
                                        </TBODY>
                                      </TABLE></TD>
                                  </TR>
                                </TBODY>
                              </TABLE></TD>
                          </TR>
                        </TBODY>
                      </TABLE>
                      <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_4.gif" 
                    border=0>
                        <TBODY>
                          <TR> 
                            <TD align=left width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_left.gif" 
                        width=9></TD>
                            <TD width="100%"><IMG height=16 
                        src="ACWSites - Links_arquivos/spacer.gif" width=1></TD>
                            <TD align=right width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_right.gif" 
                        width=9></TD>
                          </TR>
                        </TBODY>
                      </TABLE></TD>
                  </TR>
                  <TR> 
                    <TD> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_1.gif" 
                    border=0>
                        <TBODY>
                          <TR> 
                            <TD align=left width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_left.gif" 
                        width=9></TD>
                            <TD vAlign=center align=middle width="100%"><div align="center">&nbsp;<FONT 
                        class=block-title valign="bottom"><strong>Marketing</strong></FONT>&nbsp;</div></TD>
                            <TD align=right width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_right.gif" 
                        width=9></TD>
                          </TR>
                        </TBODY>
                      </TABLE>
                      <TABLE cellSpacing=0 cellPadding=0 width=165 border=0>
                        <TBODY>
                          <TR> 
                            <TD bgColor=#abb0b5> <TABLE cellSpacing=1 cellPadding=0 width="100%" 
border=0>
                                <TBODY>
                                  <TR> 
                                    <TD bgColor=#bbc8d3> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                              border=0>
                                        <TBODY>
                                          <TR> 
                                            <TD bgColor=#efefef> <TABLE cellSpacing=0 cellPadding=4 width="100%" 
                                border=0>
                                                <TBODY>
                                                  <TR> 
                                                    <TD bgcolor="#000000"><div align="center">
                                                        <p align="left"><font face="Verdana, Arial, Helvetica, sans-serif"><font color="#FFFFFF"> 
                                                          </font></font><font color="#FFFFFF" size="1" face="verdana"> 
                                                          </font> </p>
                                                        <form method="get" action="enquete2.asp" target="miniwin" onSubmit="abrejanela()">
                                                          <div align="left"></div>
                                                        </form>
                                                         
                                                        <embed src="tabela.swf" width="150" height="224"></embed> 
                                                      </div></TD>
                                                  </TR>
                                                </TBODY>
                                              </TABLE></TD>
                                          </TR>
                                        </TBODY>
                                      </TABLE></TD>
                                  </TR>
                                </TBODY>
                              </TABLE></TD>
                          </TR>
                        </TBODY>
                      </TABLE>
                      <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_4.gif" 
                    border=0>
                        <TBODY>
                          <TR> 
                            <TD align=left width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_left.gif" 
                        width=9></TD>
                            <TD width="100%"><IMG height=16 
                        src="ACWSites - Links_arquivos/spacer.gif" width=1></TD>
                            <TD align=right width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_right.gif" 
                        width=9></TD>
                          </TR>
                        </TBODY>
                      </TABLE></TD>
                  </TR>
                  <TBODY>
                    <TR> 
                      <TD> 
                        <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_1.gif" 
                    border=0>
                          <TBODY>
                            <TR> 
                              <TD align=left width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_left.gif" 
                        width=9></TD>
                              <TD vAlign=center align=middle width="100%"><div align="center">&nbsp;<FONT 
                        class=block-title valign="bottom"><STRONG>Entretenimento</STRONG></FONT></div></TD>
                              <TD align=right width=9><IMG height=29 
                        src="ACWSites - Links_arquivos/cellpic_1_right.gif" 
                        width=9></TD>
                            </TR>
                          </TBODY>
                        </TABLE>
                        <TABLE cellSpacing=0 cellPadding=0 width=165 border=0>
                          <TBODY>
                            <TR> 
                              <TD bgColor=#abb0b5> <TABLE cellSpacing=1 cellPadding=0 width="100%" 
border=0>
                                  <TBODY>
                                    <TR> 
                                      <TD bgColor=#bbc8d3> <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                              border=0>
                                          <TBODY>
                                            <TR> 
                                              <TD bgColor=#efefef> <TABLE cellSpacing=0 cellPadding=4 width="100%" 
                                border=0>
                                                  <TBODY>
                                                    <TR> 
                                                      <TD bgcolor="#000000"><div align="center"><font face="Verdana, Arial, Helvetica, sans-serif"><a href="chat.asp">Chat</a><br>
                                                          <a href="livrodevisitas.asp">Livro 
                                                          de Visitas</a><br>
                                                          <a href="forum.asp">Forum</a> 
                                                          <br>
                                                          <a href="noticias.asp">Noticias</a> 
                                                          <br>
                                                          <a href="noticias.asp">Esportes</a> 
                                                          <br>
                                                          <a href="downloads.asp">Downloads</a> 
                                                          <br>
                                                          <a href="eventos.asp">Eventos</a> 
                                                          <br>
                                                          <a href="fotos.asp">Fotos 
                                                          </a><br>
                                                          <a href="videos.asp">Videos 
                                                          </a><br>
                                                          <a href="filmes.asp">Filmes</a> 
                                                          <br>
                                                          <a href="jogos.asp">Jogos 
                                                          </a><br>
                                                          <a href="dicasdejogos.asp">Dicas 
                                                          de Jogos</a></font></div></TD>
                                                    </TR>
                                                  </TBODY>
                                                </TABLE></TD>
                                            </TR>
                                          </TBODY>
                                        </TABLE></TD>
                                    </TR>
                                  </TBODY>
                                </TABLE></TD>
                            </TR>
                          </TBODY>
                        </TABLE>
                        <TABLE cellSpacing=0 cellPadding=0 width="100%" 
                  background="ACWSites - Links_arquivos/cellpic_4.gif" 
                    border=0>
                          <TBODY>
                            <TR> 
                              <TD align=left width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_left.gif" 
                        width=9></TD>
                              <TD width="100%"><IMG height=16 
                        src="ACWSites - Links_arquivos/spacer.gif" width=1></TD>
                              <TD align=right width=9><IMG height=16 
                        src="ACWSites - Links_arquivos/cellpic_4_right.gif" 
                        width=9></TD>
                            </TR>
                          </TBODY>
                        </TABLE></TD>
                    </TR>
                  </TBODY>
                </TABLE>
                        <TABLE cellSpacing=0 cellPadding=5 width=165 border=0>
                  <TBODY>
                    <TR> 
                      
                    </TR>
                  </TBODY>
                </TABLE></TD></TR></TBODY></TABLE>
        <CENTER>
          <CENTER>
           
            <p><FONT class=footmsg><font color="#FFFFFF">Frederico Westphalen 
              - RS - CEP:98400-000 </font></FONT></p>
            <p><font color="#FFFFFF" class="footmsg"> Cel: (55) 99898544 </font><font color="#FFFFFF">E-mail:<a href="mailto:mandry@brturbo.com"><font class="footmsg"> 
              mandry@brturbo.com</font></a></font> </p>
          </CENTER>
          <p align="center"><font color="#FFFFFF">Todos os direitos reservados</font></p>
          <CENTER>
            <p><FONT color="#FF0000" face="Verdana" class=footmsg>DESIGNED BY 
              MANDRY</FONT><FONT color="#FFFFFF" class=footmsg><BR>
              </FONT></p>
            <p>&nbsp;</p>
            
            </CENTER>
          </CENTER></TR></TBODY></TABLE>
<CENTER>
  <FONT class=footmsg><font color="#FFFFFF"> </font></FONT> 
</CENTER>
</BODY></HTML>
