<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_syncimage.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## syncimage.asp
CONST IGsync_msg 	= "O arquivo foi adicionado a galeria!"
CONST IGsync_link1 	= "Editar Perfil"
CONST IGsync_link2 	= "Fechar Janela"
%>