<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_global.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## Global Settings ##

'## editimage.asp, logs.asp, system.asp, upload.asp & users.asp
CONST IG_timeout 	= "Your login session will timeout in 2 minutes. To continue your current session, please navigate to a new page."

'## header.asp
CONST IGhead_homep 	= "DCE - URI - Campus de Frederico Westphalen/RS"
CONST IGhead_lgoff 	= "Login Off"
CONST IGhead_lgon 	= "Login On"

'## menu.asp
CONST IGmenu_spo 	= "Enviar Imagens Online"
CONST IGmenu_subfrm = "Enviar Formulário"
CONST IGmenu_ua 	= "Administração de Usuários"
CONST IGmenu_anu 	= "Adicionar Novo Usuário"
CONST IGmenu_mu 	= "Manutenção de Usuário(s)"
CONST IGmenu_ulf 	= "Usuário(s) Arquivos de Log"
CONST IGmenu_smngt 	= "Manutenção do Sistema"
CONST IGmenu_smaint = "Manutenção do Sistema"
CONST IGmenu_candr  = "Compactar e Reparar Banco de Dados"
CONST IGmenu_mb  	= "PLACA DA MENSAGEM"

'## searchform.asp
CONST IGsform_sg 	= "Busca na Galeria"
CONST IGsform_but 	= "IR"
CONST IGsform_xm 	= "Busca Exata"

'## footer.asp
CONST IGfoot_his1 	= "Dentro de 7 Dias"
CONST IGfoot_his2 	= "14 Dias"
CONST IGfoot_his3 	= "21 Dias"
CONST IGfoot_pb 	= "Powered By"
%>

