<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_igallery.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## igallery.asp
CONST IG_uol 			= "VOLTAR"
CONST IG_pg1 			= "Indicando a página"
CONST IG_pg2 			= "de"
CONST IG_erfm1 			= "Usar ""Criar novo evento"" para adicionar o sub-diretório nesta pasta."
CONST IG_erfm2 			= "Não há atualmente nenhuma pasta dentro desta pasta principal.&nbsp; Para criar um novo diretório faça o Login na Administração.&nbsp; <a class=""link"" href=""login.asp"">Clique aqui</a> para logar agora."
CONST IG_ded 			= "Você deseja apagar esta pasta vazia"
CONST IG_ri 			= "Reparar ministuras quebradas nesta pasta"
CONST IG_si 			= ""
CONST IG_cnd1 			= "Criar um novo evento"
CONST IG_rnd1 			= "Renomear este evento"
CONST IG_edm 			= "Não há atualmente nenhuma imagem dentro deste evento."
CONST IG_upttf1 		= "Enviar Imagens para esta pasta"
CONST IG_upttf2 		= "Pasta Principal"
CONST IG_but1 			= "Criar"
CONST IG_but2 			= "Renomear"

'## toolbar.asp
CONST IGt_editimage 	= "Editar Imagem"
CONST IGt_viewimage 	= "Visualizar Imagem"
CONST IGt_rotateimagel 	= "Rodar Imagem 90&ordm; Esquerda"
CONST IGt_centerimage 	= "Centralizar Imagem"
CONST IGt_rotateimager 	= "Rodar Imagem 90&ordm; Direita"
CONST IGt_dwnimage 		= "Download Imagem"

'## igallery.inc
CONST IGi_add 			= "Adicionado"
CONST IGi_ht 			= "Altura"
CONST IGi_wd 			= "Largura"
CONST IGi_un 			= "Indefinido"
CONST IGi_mod 			= "Mod."
CONST IGi_sz 			= "Tamanho"
CONST IGi_adjprop 		= "Editar Propriedades"
CONST IGi_view 			= "Clique aqui para visualizar"
CONST IGi_vote 			= "Clique aqui para votar"
CONST IGi_tv 			= "Total de voto(s)"
CONST IGi_views 		= "Visualizações"
CONST IGi_dwnaudio 		= "Download Arquivo de Audio"
CONST IGi_editaudio 	= "Edit Arquivo de Audio"
CONST IGi_dwnvideo 		= "Download Arquivo de Video"
CONST IGi_editvideo 	= "Editar Arquivo de Video"
CONST IGi_dwnld 		= "Download"
CONST IGi_dwnlds 		= "Downloads"
CONST IGi_f 			= "Arquivo"
CONST IGi_desc 			= "Descrição"
CONST IGi_unkn 			= "Indefinido"
CONST IGi_delunkn 		= "Deletar Arquivo Indefinido"
%>

