<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_login.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## login.asp
CONST IGlog_both 	= "Os campos de Usuário e Senha estão em branco!"
CONST IGlog_name 	= "O campo usuário esta em branco!"
CONST IGlog_pass 	= "O campo senha esta em branco!"
CONST IGlog_nof 	= "A confirmação não é válida!"
CONST IGlog_na 		= "Requer Autenticação!"
CONST IGlog_auth 	= "Requer Autenticação!"
CONST IGlog_usern 	= "Usuário"
CONST IGlog_passw 	= "Senha"
CONST IGlog_rem 	= "Lembre-me"
CONST IGlog_but1 	= "Entrar"
%>