<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_editimage.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## editimage.asp
CONST IGei_click 	= "Clique aqui para renomear o arquivo"
CONST IGei_rtnfldr 	= "Retornar a pasta"
CONST IGei_adj1 	= "Ajustar Tamanho e Rotação"
CONST IGei_adj2 	= "Ajustar Tamanho da Imagem"
CONST IGei_img1 	= "Clicar para Visualizar"
CONST IGei_img2 	= "Visualizar"
CONST IGei_dwnaudio = "Download Arquivo de Audio"
CONST IGei_dwnvideo = "Download Arquivo de Video"
CONST IGei_f 		= "Arquivo"
CONST IGei_unkn 	= "Indefinido"
CONST IGei_title 	= "Título da Imagem"
CONST IGei_desc 	= "Descrição da Imagem"
CONST IGei_max 		= "Máximo"
CONST IGei_maxchar 	= "Máximo de Caracteres"
CONST IGei_move1 	= "Mover o Arquivo para"
CONST IGei_move2 	= "Mover para a Pasta"
CONST IGei_copy1 	= "Copiar este Arquivo para"
CONST IGei_copy2 	= "Copiar para a pAsta"
CONST IGei_del1 	= "Apagar arquivo desta Pasta!"
CONST IGei_del2 	= "Confirmar"
CONST IGei_msg1 	= "Detalhes da Imagem salvos com sucesso!"
CONST IGei_msg2 	= "Imagem renomeada com sucesso!"
CONST IGei_but1 	= "Renomear"
CONST IGei_but2 	= "Atualizar"
CONST IGei_but3 	= "Mover"
CONST IGei_but4 	= "Copiar"
CONST IGei_but5 	= "Deletar Imagem"
%>