<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_users.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## users.asp
CONST IGusr_add 		= "Adicionar novo Administrador"
CONST IGusr_addmsg 		= "Preencher o formulário abaixo para adicionar um administrador novo à base de dados administrativa da Galeria. Por favor Nota: Todos os campos são requeridos ao adicionar um perfil do administrador."
CONST IGusr_form1 		= "Primeiro Nome"
CONST IGusr_form2 		= "Segundo Nome"
CONST IGusr_form3 		= "Endereço de Email"
CONST IGusr_form4 		= "Usuário"
CONST IGusr_form5 		= "Senha"
CONST IGusr_form6a 		= "Privilégio"
CONST IGusr_form6b 		= "Selecionar Nível de Acesso"
CONST IGusr_form6c 		= "Visualizar e Editar"
CONST IGusr_form6d 		= "Administrador Total da Galeria"
CONST IGusr_but1 		= "Adicionar Novo Administrador"
CONST IGusr_but2 		= "Editar Perfil de Usuário"
CONST IGusr_err1 		= "O <b>""Primeiro Nome""</b> Campo Obrigatório!"
CONST IGusr_err2 		= "O <b>""Segundo Nome""</b> Campo Obrigatório!"
CONST IGusr_err3 		= "O <b>""Endereço de Email""</b> O endereço de email é inválido."
CONST IGusr_err4 		= "O <b>""Usuário""</b> Campo Obrigatório!"
CONST IGusr_err5 		= "O <b>""Senha""</b> Campo Obrigatório!"
CONST IGusr_err6 		= "O <b>""Nível Usuário""</b> Campo Obrigatório!"
CONST IGusr_err 		= "Erro!"
CONST IGusr_errmsg 		= "Tem um estado de erro que processa seu pedido!&nbsp; <b>Nota:</b>  Todos os campos obrigatórios para o envio do formulário."
CONST IGusr_folw 		= "Reveja por favor os seguintes campos!"
CONST IGusr_click 		= "Clique aqui para corrigir o problema."
CONST IGusr_addsuc 		= "Novo Administrador Adicionado"
CONST IGusr_addsucmsg 	= "O perfil do administrador foi adicionado com sucesso à base de dados.&nbsp; <a class=""linkmed"" href=""users.asp"">Clique aqui</a> para retornar a ""Administração""."
CONST IGusr_upd 		= "Atualizar Perfil do Administrador"
CONST IGusr_updmsg 		= "<b>Nota:</b>  Todos os campos são requeridos ao atualizar um perfil dos administradores.&nbsp; Para suprimir um perfil retorne à tela precedente e clique no ""X"" tecla ao lado do perfil que você quer excluir.&nbsp; <a class=""linkmed"" href=""javascript: history.back(-1);"">Clique aqui</a> para retornar a página anterior."
CONST IGusr_updsuc 		= "Atualizar Perfil do Administrador"
CONST IGusr_updsucmsg 	= "O perfil do administrador foi atualizado com sucesso.&nbsp; <a class=""linkmed"" href=""users.asp"">Clique aqui</a> para retornar a ""Administração""."
CONST IGusr_warn 		= "Você tem certeza que deseja excluir o \""User\"" da Galeria?  Todas as informações serão perdidas!"
CONST IGusr_del 		= "Deletar Perfil do Administrador"
CONST IGusr_delmsg 		= "O administrador foi deletado com sucesso no banco de dados.&nbsp; <a class=""link"" href=""users.asp"">Clique aqui</a> para retornar para ""Administração""."
CONST IGusr_mng 		= "Controle Administradores Atuais"
CONST IGusr_mngmsg 		= "Para editar o Administrador clique no lápis.&nbsp; Para deletar o administrador clique no ""X"" ao lado do administrador que você deseja deletar."
CONST IGusr_mngg1 		= "Último Nome, Primeiro Nome"
CONST IGusr_mngg2 		= "Endereço de Email"
CONST IGusr_mngg3 		= "Adicionado"
CONST IGusr_mngg4 		= "Editar Administrador."
CONST IGusr_mngg5 		= "Apagar Administrador."
CONST IGusr_page 		= "Registros Por A Página - Indicando A Página"
%>