<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_search.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## search.asp
CONST IGsrch_sr 		= "Buscar Resultados"
CONST IGsrch_pg 		= "Página"
CONST IGsrch_null1 		= "Você esta procurando por"
CONST IGsrch_null2 		= "Busca sem resultados!&nbsp;"
CONST IGsrch_null3 		= "O campo de busca esta vazio!"

'## searchresults.asp
CONST IGsrslt_nm 		= "Nome"
CONST IGsrslt_indx  	= "Indexado"
CONST IGsrslt_title 	= "Título"
CONST IGsrslt_desc 		= "Descrição"
CONST IGsrslt_ctvi 		= "Clique para visualizar a imagem"
CONST IGsrslt_dwnaudio 	= "Download Arquivo de Audio"
CONST IGsrslt_dwnvideo 	= "Download Arquivo de Video"
CONST IGsrslt_dir 		= "Diretório"
CONST IGsrslt_eimg 		= "Editar Imagem"
CONST IGsrslt_vimg 		= "Visualizar Imagem"
CONST IGsrslt_dimg 		= "Download da Imagem"
CONST IGsrslt_cte 		= "Clique para Ampliar"
CONST IGsrslt_edtaudio 	= "Editar Arquivo de Audio"
CONST IGsrslt_edtvideo 	= "Editar Arquivo de Video"
CONST IGsrslt_dwn 		= "Download"
CONST IGsrslt_f 		= "Arquivo"
%>