<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_viewphoto.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## viewphoto.asp
CONST IGvp_dimg 	= "Download da Imagem"
CONST IGvp_eimg 	= "Imagem por Email"
CONST IGvp_pimg 	= "Imprimir Imagem"
CONST IGvp_rsmenu 	= "Redimensionar menu da imagem"
CONST IGvp_aemenu 	= "Efeitos Artisticos no Menu"
CONST IGvp_close 	= "Fechar Visualizador de Imagem"
CONST IGvp_audio 	= "Arquivo de Audio"
CONST IGvp_dwnaudio = "Download Arquivo de Audio"
CONST IGvp_video 	= "Arquivo de Video"
CONST IGvp_dwnvideo = "Download Arquivo de Video"
CONST IGvp_unknwn 	= "Indefinido"
CONST IGvp_f 		= "Indefinido"
CONST IGvp_pi 		= "Imagem Anterior"
CONST IGvp_start 	= "Iniciar SLIDES"
CONST IGvp_stop 	= "Parar SLIDES"
CONST IGvp_ni 		= "Próxima Imagem"
CONST IGvp_rszmsg 	= "Esta imagem pode ser redimensionada com a tela.&nbsp; <u>Clique aqui</u> para redimensionar a imagem para o seu tamanho normal."
CONST IGvp_p1 		= "Imprimir Tela"
CONST IGvp_p2 		= "Impressora Amigável"
CONST IGvp_zoom1 	= "Zoom - 25%"
CONST IGvp_zoom2 	= "Zoom - 50%"
CONST IGvp_zoom3 	= "Zoom - 75%"
CONST IGvp_zoom4 	= "Zoom + 25%"
CONST IGvp_zoom5 	= "Zoom + 50%"
CONST IGvp_zoom6 	= "Zoom + 75%"
CONST IGvp_zoom7 	= "Zoom + 100%"
CONST IGvp_zoom8 	= "Ajuste À Tela"
CONST IGvp_zoom9 	= "Reverter ao Tamanho Normal"
CONST IGvp_eff1 	= "Blur"
CONST IGvp_eff2 	= "Emboss"
CONST IGvp_eff3 	= "Engrave"
CONST IGvp_eff4 	= "Grayscale"
CONST IGvp_eff5 	= "Inverter"
CONST IGvp_eff6 	= "Mirror"
CONST IGvp_eff7 	= "Pixelate"
CONST IGvp_eff8 	= "Rotação - 180&ordm;"
CONST IGvp_eff9 	= "Raio - X"
CONST IGvp_eff10 	= "Reverter"
%>