<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_vote.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## vote.asp
CONST IGvote_err 		= "Erro!"
CONST IGvote_errmsg 	= "O arquivo que você tentou postar não existe.&nbsp; Para maiores informações contate o"
CONST IGvote_sysadm 	= "administrador do sistema"
CONST IGvote_close 		= "Fechar esta Janela"
CONST IGvote_suc 		= "Voto Gravado!"
CONST IGvote_sucmsg 	= "Seu voto foi executado com sucesso!.&nbsp; Obrigado pela sua contribuição!"
CONST IGvote_perr 		= "Erro Processamento!"
CONST IGvote_perrmsg 	= "Você já votou neste artigo...para mais informações contate o"
CONST IGvote_vb 		= "Voting Booth"
CONST IGvote_af 		= "Arquivo de Audio"
CONST IGvote_vf 		= "Arquivo de Video"
CONST IGvote_but 		= "Molde o seu Voto!"
%>