<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_photoproperties.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## photoproperties.asp
CONST IGpp_adj1 	= "Nota"
CONST IGpp_adj2 	= "A imagem foi feita sob medida de"
CONST IGpp_adj3 	= "pixels para"
CONST IGpp_adj4 	= "pixels"
CONST IGpp_shrp1 	= "A imagem rotacionada para 90&deg;"
CONST IGpp_shrp2 	= "CCW" ' Counter Clockwise
CONST IGpp_shrp3 	= "CW"  ' Clockwise
CONST IGpp_shrp4 	= "A imagem pode ser rotacionada."
CONST IGpp_opmsg1 	= "A dimensão desta imagem é ajustada atualmente em"
CONST IGpp_opmsg2 	= "pixels"
CONST IGpp_opmsg3 	= "Para suportar a maioria monitores os ajustes que nós o recomendamos nesta imagem é uma <b>largura</b> de 800 pixels e a <b>altura</b> em 600 pixels."
CONST IGpp_opmsg4 	= "Esta imagem é feita sob medida apropriadamente para a maioria de monitores."
CONST IGpp_fldset1 	= "Redimensionar Image"
CONST IGpp_frm1 	= "Escalar Image @"
CONST IGpp_frm1a 	= "Selecionar porcentagem"
CONST IGpp_frm1b 	= "pixels"
CONST IGpp_frm2 	= "Nova largura"
CONST IGpp_frm2a 	= "Pixels"
CONST IGpp_frm3 	= "Nova altura"
CONST IGpp_frm3a 	= "Pixels"
CONST IGpp_frm4 	= "Sharpen Imagem"
CONST IGpp_frm4a 	= "(deve ser > 100)"
CONST IGpp_frm5 	= "Rodar Imagem"
CONST IGpp_frm5a 	= "90&deg; Esquerda"
CONST IGpp_frm5b 	= "90&deg; Direita"
CONST IGpp_frm5c 	= "Sem Rotação"
CONST IGpp_cursize 	= "Tamanho Atual"
CONST IGpp_viewfi 	= "Visualizar Imagens Inteiras"
CONST IGpp_but 		= "Aplicar Mudanças"
%>