<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_sendtofriend.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## sendtofriend.asp
CONST IGstf_alrt1 	= "Por favor entre com um valor no campo \""Seu nome\""!"
CONST IGstf_alrt2 	= "O campo de \""E-mail\"" contém um endereço inválido."
CONST IGstf_alrt3 	= "Por favor entre com um valor no campo \""Nome do seu amigo\""!"
CONST IGstf_alrt4 	= "O campo \""E-mail do seu amigo\"" contém um endereço inválido."
CONST IGstf_emsg1 	= "Foto enviada pela Galeria de fotos da Vitrola"
CONST IGstf_emsg2 	= "A seguinte imagem foi enviada no pedido de"
CONST IGstf_emsg3 	= "Mensagem Pessoal"
CONST IGstf_emsg4 	= "Tenha um Bom dia!"
CONST IGstf_head1 	= "Mensagem Enviada com Sucesso!"
CONST IGstf_sucs1 	= "Parabéns"
CONST IGstf_sucs2 	= "A imagem que você selecionou foi entregada com sucesso a"
CONST IGstf_sucs3 	= "<a class=""link"" href=""igallery.asp"">Clique Aqui</a> para retornar a pasta da Galeria."
CONST IGstf_fail1 	= "O formulário <b>não</b> foi enviado.&nbsp; Por favor tente novamente."
CONST IGstf_fail2 	= "Erro"
CONST IGstf_head2 	= "Enviar Foto por E-mail"
CONST IGstf_etptxt 	= "Envie esta foto agora mesmo para algum amigo seu preenchendo os campos abaixo. Atenção todos os campos são obrigatórios."
CONST IGstf_frm1 	= "Seu nome"
CONST IGstf_frm2 	= "Seu E-mail"
CONST IGstf_frm3 	= "Nome do seu amigo"
CONST IGstf_frm4 	= "E-mail do seu amigo"
CONST IGstf_frm5 	= "Digite uma descrição da imagem para a pessoa que você vai enviar!"
CONST IGstf_but1 	= "Enviar Imagem"
%>