<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_logs.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## logs.asp
CONST IGlgs_alrt1 	= "Você tem certeza que deseja deletar os \""Log(s)\"" no banco de dados?  Todas as informações serão perdidas!"
CONST IGlgs_alrt2 	= "Você tem certeza que deseja deletar os \""Log\"" no banco de dados?  Todas as informações serão perdidas!"
CONST IGlgs_deltitl = "Usuário(s) Logado(s) Deletado(s)"
CONST IGlgs_delmsgl = "Os ""User Log"" que você selecionou foram deletados com sucesso!.&nbsp; <a class=""link"" href=""logs.asp"">Clique aqui</a> para retornar ao ""User Access Log""."
CONST IGlgs_delmsg2 = "Os ""User Logs"" que você selecionou foram deletados com sucesso!.&nbsp; <a class=""link"" href=""logs.asp"">Clique aqui</a> para retornar ao ""User Access Log""."
CONST IGlgs_titl 	= "Usuário(s) Logado(s)"
CONST IGlgs_msgl 	= "Listado abaixo os ""Usuários Logados"" no arquivo.&nbsp; Para deletar os usuários selecionados clique no ""X""."
CONST IGlgs_msg2 	= "Não há atualmente nenhum usuário logado na pasta!"
CONST IGlgs_grd1 	= "Nome"
CONST IGlgs_grd2 	= "Endereço de Email"
CONST IGlgs_grd3 	= "Data do último envio"
CONST IGlgs_grd4 	= "Logs"
CONST IGlgs_but 	= "Deletar os log(s) selecionados"
CONST IGlgs_page1 	= "Registros por página - Indicando a página"
CONST IGlgs_page2 	= "de"
%>