<%
'####################################
'## Application:   Blue-Collar Productions
'## File Name:     lang_submitphotos.inc (Language File)
'## File Version:  i-Gallery
'## Notice:        This code has limited warranties. Please see http://www.b-cp.com for details.
'####################################
%>

<%
'## submitphotos.asp
CONST IGsp_mail1 	= "i-Gallery Photo Administrator"
CONST IGsp_mail2 	= "i-Gallery - New Photo Submission"
CONST IGsp_mail3 	= "A new photo has been forwarded to you for possible inclusion in the gallery.&nbsp; The image is attached for your convenience."
CONST IGsp_msg1 	= "Greetings"
CONST IGsp_msg2 	= "The photo you attached has been successfully emailed to us.&nbsp; Thank you for your submission.&nbsp; We will review your photo and if valid we will consider it for inclusion in our gallery.&nbsp; <a class=""link"" href=""igallery.asp"">Click Here</a> to return to the main gallery."
CONST IGsp_msg3 	= "Best Regards"
CONST IGsp_msg4 	= "Photo Administrator"
CONST IGsp_err1 	= "ERROR"
CONST IGsp_err2 	= "The ""Photo Submission"" form was <b>NOT</b> sent successfully.&nbsp; We could be experiencing temporary server problems.&nbsp; Please try again at a later time."
CONST IGsp_err3 	= "The ""Photo Submission"" form was <b>NOT</b> sent successfully.&nbsp; The photo you attempted to email us exceeds the maximum allowed upload size of"
CONST IGsp_err4 	= "The email process has been terminated."
CONST IGsp_err5 	= "Best Regards"
CONST IGsp_err6 	= "Photo Administrator"
CONST IGsp_alrt1 	= "The \""File Attachment\"" field is required!  Please select an image attachment by clicking on the browse button."
CONST IGsp_alrt2 	= "The \""File Type\"" you have requested is not allowed!  Supported file types are:"
CONST IGsp_alrt3 	= "The \""Your Name\"" field was left empty!  This is a required field when submitting photo entries."
CONST IGsp_alrt4 	= "The \""Your Email Address\"" field contains an invalid email address or the field was left blank."
CONST IGsp_titl 	= "Photo Submission"
CONST IGsp_admsg1 	= "Almost Done!"
CONST IGsp_admsg2 	= "Review the information you submitted below for accuracy and if all looks good click on the ""Browse"" button to attach your photo.&nbsp; If not you can click on the ""&#171;&#171; Step One"" button to make corrections then resubmit.&nbsp; When your ready click on the "'Submit Photo!"" button and your image will be processed for review!"
CONST IGsp_frml 	= "Your Name"
CONST IGsp_frm2 	= "Email Address"
CONST IGsp_frm3 	= "Description"
CONST IGsp_frm3a 	= "No description available!"
CONST IGsp_step2 	= "Step Two"
CONST IGsp_frm4 	= "Attach Photo"
CONST IGsp_frm4a 	= "Maximum Upload Size"
CONST IGsp_but1 	= "Submit Photo!"
CONST IGsp_but2 	= "&#171;&#171; Step One"
CONST IGsp_but3 	= "Step Two &#187;&#187;"
CONST IGsp_pnmsg1 	= "Please Note"
CONST IGsp_pnmsg2 	= "Your are about to email a photo to the gallery administrator. The image you are attaching to your email may not exceed"
CONST IGsp_pnmsg3 	= "in size. Please check the size of your photo before continuing to avoid any processing delays."
CONST IGsp_opnmsg1  = "Would you like your photo(s) to appear in our online photo gallery?&nbsp; Use the form below to submit them to us for possible inclusion.&nbsp; Please make sure that your photos do not exceed our maximum allowed size of"
CONST IGsp_opnmsg2  = "We look forward to viewing your photos!"
CONST IGsp_step1 	= "Step One"
CONST IGsp_frm5 	= "Your Name"
CONST IGsp_frm6 	= "E-Mail Address"
CONST IGsp_frm7 	= "Brief Photo Description"
CONST IGsp_frm7a 	= "Optional Field!&nbsp; 200 Character Max."
CONST IGsp_req 		= "Required Field!"
CONST IGsp_max 		= "Max Char."
CONST IGsp_xtra 	= "<b>Please Note:</b><br>When you use our ""Photo Submission"" page, we ask for your name and email address.&nbsp; This information is only used to send your message and is not stored by our Web for any other purpose nor is it shared with any outside parties.&nbsp; For more information please review our <a class=""linksm"" href=""privacy.asp"">privacy policy</a>."
CONST IGsp_apperr 	= "The Email application you have picked in the system set-up does not support this page!"
%>