<html>
<head>
<LINK href="css/styles.css" type=text/css rel=stylesheet>
<title>DCE - URI - Campus de Frederico Westphalen/RS</title>
</HEAD>
<BODY bgColor=#ffffff leftMargin=0 topMargin=20 rightMargin=0>

<TABLE cellSpacing=0 cellPadding=0  align="center" width="80%" height="95%" bgColor=#ffffff border=0 align="center">
<TBODY>
<TR height=85%>

<TD style="BACKGROUND-REPEAT: no-repeat" valign="top" align="center">
<BR><BR><BR>

