<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD><TITLE>Vista M&oacute;veis</TITLE>
<META http-equiv=Content-Type content="text/html; charset=iso-8859-1">
<LINK href="Radio95.9FM_arquivos/default.css" type=text/css rel=STYLESHEET>
<!--Code generated by Cool Web Scrollbars from Harmony Hollow Software-->
<!--http://www.harmonyhollow.net-->
<STYLE type="text/css">
<!--
BODY {
scrollbar-face-color:#0080C0;
scrollbar-highlight-color:#0080C0;
scrollbar-3dlight-color:#454545;
scrollbar-darkshadow-color:#454545;
scrollbar-shadow-color:#454545;
scrollbar-arrow-color:#FFFFFF;
scrollbar-track-color:#454545;
}
-->
</STYLE>
<!--End Cool Web Scrollbars code-->

<META content="MSHTML 6.00.2600.0" name=GENERATOR></HEAD>
<BODY bgColor=#f6f6f6 text="#000000" link="#000000" vlink="#000000" alink="#000000" leftMargin=0 topMargin=0 marginwidth="0" marginheight="0">
<font size="1" face="Verdana, Arial, Helvetica, sans-serif"> </font> 
<div align="center"> 
  <p>&nbsp;</p>
  <p><img src="menornn.gif" width="120" height="109"> </p>
  <p><font color="#000000" size="3" face="Verdana, Arial, Helvetica, sans-serif">Administra&ccedil;&atilde;o 
    das Not&iacute;cias</font></p>
  <form method="POST" action="admin.asp?flag=1">
    <font color="#000000"> 
    <%
flag = request.querystring("flag")

if flag = 1 then

If IsEmpty(request.form("ID")) then 

			response.write "<br><br><br><br><br><br><p align=center>"
			response.write "<table border=1 cellpadding=3 cellspacing=0 width=423 bordercolor=#000000><tr><td width=415> <p align=center><font face=Verdana size=2>User Error</font></p></td></tr>"
			response.write "<tr><td width=415 bgcolor=#C0C0C0><p align=center><font face=Verdana size=2>If you want to delete an"
			response.write " entry, check the checkbox<br>Hit the back button and try again.</font></p></td></tr></table>"
			response.end
		
End If
		
set rs = nothing
ID = request.form("ID")
		set conn = server.createobject("adodb.connection")
		DSNtemp="DRIVER={Microsoft Access Driver (*.mdb)}; "
    	DSNtemp=dsntemp & "DBQ=" & server.mappath("news/journal.mdb")
    	conn.Open DSNtemp
		For each record in request("ID")
    		sqlstmt = "DELETE * from journal WHERE ID=" & record
			Set RS = conn.execute(sqlstmt)
		Next

end if
%>
    <br>
    </font> 
    <div align="center"> 
      <center>
        <table border="1" cellpadding="3" cellspacing="0" width="423" bordercolor="#000000">
          <tr> 
            <td width="415"><div align="center"><font color="#000000" size="2" face="Verdana">Administra&ccedil;&atilde;o 
                do Conte&uacute;do</font></div></td>
          </tr>
          <%
set rs = nothing
DSNtemp="DRIVER={Microsoft Access Driver (*.mdb)}; "
          DSNtemp=dsntemp & "DBQ=" & server.mappath("news/journal.mdb")
          sqlstmt = "SELECT * FROM journal ORDER BY id DESC"
          Set rs = Server.CreateObject("ADODB.Recordset")
          rs.Open sqlstmt, DSNtemp, 3, 3
TotalRecs = rs.recordcount
x = 0
For x = 1 to 9999
	If rs.eof then
		Exit For
	Else
		date1 = rs("pdate")
		id = rs("ID")
		name = rs("pname")
	  	link = "<a href='view.asp?id=" & id & "'>" & date1 & "</a>"
		description = name
   %>
          <tr> 
            <td width="415"><font color="#000000"> 
              <input type="checkbox" name="ID" value="<% =id %>">
              <font face="Verdana" size="2"> 
              <% =link%>
              &nbsp; -- 
              <% =description%>
              </font></font></td>
          </tr>
          <%
rs.MoveNext
End If
Next%>
        </table>
      </center>
    </div>
    <p align="center"> <font color="#000000"> 
      <input type="submit" value="Deletar" name="B1">
      <br>
      <br>
      <font face="Verdana" size="2"><a href="submit.asp">Nova Not&iacute;cia</a></font></font></p>
  </form>
  <p>&nbsp; </p>
</div>
</BODY></HTML>
