<%
'***************************************
'*  Script written by nexusjnr
'*  I am planning on adding more
'*  stuff  to this, so no nasty
'*  comments please.
'*  please send comments, suggestions
'*  to mail@nexusjnr.co.uk.
'* feel free to distribute this
'* code...a mention would be nice
'***************************************
%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD><TITLE>Admi9nistra&ccedil;&atilde;o dos pedidos de m&uacute;sicas R&aacute;dio Luz e Alegria</TITLE>
<META http-equiv=refresh content=900>
<META http-equiv=Content-Type content="text/html; charset=iso-8859-1">
<LINK href="Radio95.9FM_arquivos/default.css" type=text/css rel=STYLESHEET>
<!--Code generated by Cool Web Scrollbars from Harmony Hollow Software-->
<!--http://www.harmonyhollow.net-->
<STYLE type="text/css">
<!--
BODY {
scrollbar-face-color:#0080C0;
scrollbar-highlight-color:#0080C0;
scrollbar-3dlight-color:#454545;
scrollbar-darkshadow-color:#454545;
scrollbar-shadow-color:#454545;
scrollbar-arrow-color:#FFFFFF;
scrollbar-track-color:#454545;
}
-->
</STYLE>
<!--End Cool Web Scrollbars code-->

<META content="MSHTML 6.00.2600.0" name=GENERATOR></HEAD>
<BODY bgColor=#EAEDF4 text="#000000" link="#000000" vlink="#000000" alink="#000000" leftMargin=0 topMargin=0 marginwidth="0" marginheight="0">
<font size="1" face="Verdana, Arial, Helvetica, sans-serif"> </font> 
<div align="center"> 
  <p>&nbsp;</p>
  <p><font size="3" face="Verdana, Arial, Helvetica, sans-serif">M&uacute;sicas 
    Administra&ccedil;&atilde;o</font></p>
  <p><img src="fundofm.jpg" width="280" height="201"></p>
  <table width="423" border="0" align="left" cellpadding="3" cellspacing="0" bordercolor="#0099CC">
    <tr> 
      <td width="415"><div align="center"><font color="#000000" size="1" face="Verdana">M&uacute;sicas 
          Pedidas</font></div></td>
    </tr>
    <%
DSNtemp="DRIVER={Microsoft Access Driver (*.mdb)}; "
          DSNtemp=dsntemp & "DBQ=" & server.mappath("journal.mdb")
          sqlstmt = "SELECT * FROM journal ORDER BY id DESC"
          Set rs = Server.CreateObject("ADODB.Recordset")
          rs.Open sqlstmt, DSNtemp, 3, 3
TotalRecs = rs.recordcount
x = 0
For x = 1 to 9999
	If rs.eof then
		Exit For
	Else
		date1 = rs("pdate")
		id = rs("ID")
		name1 = rs("pname")
	  	link = "<a href='view.asp?id=" & id & "'>" & date1 & "</a>"
		description = name1
   %>
    <tr> 
      <td width="415"><font color="#000000" size="1" face="Verdana"> 
        <% =link%>
        &nbsp; -- 
        <% =description%>
        </font></td>
    </tr>
    <%
rs.MoveNext
End If
Next%>
  </table>
  <p>&nbsp;</p>
</div>
</BODY></HTML>
