vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|24 Jun 2008 17:57:19 -0000
vti_extenderversion:SR|4.0.2.8912
vti_filesize:IR|22317
vti_backlinkinfo:VX|santaluzia/lancamentos.asp santaluzia/sessoes.asp santaluzia/subdep.asp santaluzia/compra.asp santaluzia/produtos.asp santaluzia/promocoes.asp
vti_cacheddtm:TX|24 Jun 2008 17:57:19 -0000
vti_cachedlinkinfo:VX|H|default.asp H|default.asp S|voltando.gif H|default.asp S|<%=dirlingua%>/imagens/ofertasdodia2.gif H|sessoes.asp H|javascript:\\ history.back() S|voltando.gif A|comprar.asp S|produtos/<%=rs("impeq")%> H|produtos.asp S|<%=dirlingua%>/imagens/detalhes.gif A|comprar.asp S|produtos/<%=rs3("impeq")%> H|produtos.asp S|<%=dirlingua%>/imagens/detalhes.gif H|sessoes.asp H|sessoes.asp H|sessoes.asp H|sessoes.asp H|javascript:\\ history.back() S|voltando.gif A|comprar.asp S|produtos/<%=rs("impeq")%> H|produtos.asp S|<%=dirlingua%>/imagens/detalhes.gif A|comprar.asp S|produtos/<%=rs("impeq")%> H|produtos.asp S|<%=dirlingua%>/imagens/detalhes.gif S|<%=dirlingua%>/imagens/ofertasbaixo2.gif H|javascript:\\ history.back() S|voltando.gif
vti_cachedsvcrellinks:VX|FHUS|santaluzia/default.asp FHUS|santaluzia/default.asp FSUS|santaluzia/voltando.gif FHUS|santaluzia/default.asp USUS|<%=dirlingua%>/imagens/ofertasdodia2.gif FHUS|santaluzia/sessoes.asp SHUS|javascript:\\ history.back() FSUS|santaluzia/voltando.gif FAUS|santaluzia/comprar.asp USUS|produtos/<%=rs("impeq")%> FHUS|santaluzia/produtos.asp USUS|<%=dirlingua%>/imagens/detalhes.gif FAUS|santaluzia/comprar.asp USUS|produtos/<%=rs3("impeq")%> FHUS|santaluzia/produtos.asp USUS|<%=dirlingua%>/imagens/detalhes.gif FHUS|santaluzia/sessoes.asp FHUS|santaluzia/sessoes.asp FHUS|santaluzia/sessoes.asp FHUS|santaluzia/sessoes.asp SHUS|javascript:\\ history.back() FSUS|santaluzia/voltando.gif FAUS|santaluzia/comprar.asp USUS|produtos/<%=rs("impeq")%> FHUS|santaluzia/produtos.asp USUS|<%=dirlingua%>/imagens/detalhes.gif FAUS|santaluzia/comprar.asp USUS|produtos/<%=rs("impeq")%> FHUS|santaluzia/produtos.asp USUS|<%=dirlingua%>/imagens/detalhes.gif USUS|<%=dirlingua%>/imagens/ofertasbaixo2.gif SHUS|javascript:\\ history.back() FSUS|santaluzia/voltando.gif
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
