<%
Option Explicit
Dim sql,rsUsers,count
%>
<!--#include file="conn.asp"-->
<%
sql = "SELECT * FROM users where stats = 1 ORDER BY username"
Set rsUsers = Server.CreateObject("ADODB.Recordset")
rsUsers.Open sql, conn, 3, 3
%>
<LINK href="default.css" type=text/css rel=STYLESHEET>
<html>
<head>
<title>User List</title>
</head>
<meta HTTP-EQUIV="refresh" CONTENT="30;URL=userview2.asp">
<!--Code generated by Cool Web Scrollbars from Harmony Hollow Software-->
<!--http://www.harmonyhollow.net-->
<STYLE type="text/css">
<!--
BODY {
scrollbar-face-color:#000000;
scrollbar-highlight-color:#000000;
scrollbar-3dlight-color:#FFFFFF;
scrollbar-darkshadow-color:#000000;
scrollbar-shadow-color:#FFFFFF;
scrollbar-arrow-color:#FFFFFF;
scrollbar-track-color:#000000;
}
-->
</STYLE>
<!--End Cool Web Scrollbars code-->


<body bgcolor="#454545" link="#DD0000" vlink="#DD0000" alink="#000000">
<p align="center"><font color="#FFFFFF" size="1" face="Verdana, Arial, Helvetica, sans-serif">Usu&aacute;rios 
  Online</font></p>
<font face="arial,helvetica" size=2>
<table cellpadding="2" cellspacing="0" border="0" bordercolor="#B4B4B4" width="100%">
  <%
count = 1
while not rsUsers.EOF
%>
  <tr> 
    <td><font color="#FFFFFF" size="1" face="Verdana, Arial, Helvetica, sans-serif"> 
      <img src="bp.gif" width="9" height="9"> - <%= rsUsers("username") %></font></td>
  </tr>
  <%
rsUsers.Movenext
count = count + 1
wend
%>
</table>
</font> 
</body>
</html>

