DROP TABLE IF EXISTS `cadastro`;
CREATE TABLE `cadastro` (
  `codigo` int(5) NOT NULL auto_increment,
  `etelefone2` char(255) NOT NULL default '',
  `razao` char(255) NOT NULL default '',
  `email` char(255) NOT NULL default '',
  `site` char(255) NOT NULL default '',
  `fantasia` char(255) NOT NULL default '',
  `endereco` char(255) NOT NULL default '',
  `bairro` char(255) NOT NULL default '',
  `cidade` char(255) NOT NULL default '',
  `estado` char(255) NOT NULL default '',
  `cep` char(255) NOT NULL default '',
  `cnpj` char(255) NOT NULL default '',
  `estadual` char(255) NOT NULL default '',
  `telefone` char(255) NOT NULL default '',
  `celular` char(255) NOT NULL default '',
  `fax` char(255) NOT NULL default '',
  `enome` char(255) NOT NULL default '',
  `etelefone` char(255) NOT NULL default '',
  `econtato` char(255) NOT NULL default '',
  `banco1` char(255) NOT NULL default '',
  `conta1` char(255) NOT NULL default '',
  `telbanco1` char(255) NOT NULL default '',
  `agencia1` char(255) NOT NULL default '',
  `gerente1` char(255) NOT NULL default '',
  `banco2` char(255) NOT NULL default '',
  `conta2` char(255) NOT NULL default '',
  `telbanco2` char(255) NOT NULL default '',
  `agencia2` char(255) NOT NULL default '',
  `gerente2` char(255) NOT NULL default '',
  `dados` char(255) NOT NULL default '',
  `imagem` char(255) NOT NULL default '',
  `marcas` char(255) NOT NULL default '',
  `arquivo` char(255) NOT NULL default '',
  `arquivo_nome` char(255) NOT NULL default '',
  `oia` char(255) NOT NULL default '',
  `login` varchar(255) NOT NULL default '',
  `senha` varchar(255) NOT NULL default '',
   PRIMARY KEY  (`codigo`)
) TYPE=MyISAM AUTO_INCREMENT=1 ;