<?php
/***************************************************************************
 *                         lang_faq.php [portuguese_br]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id: lang_faq.php,v 1.1.2.3 2002/11/13 23:28:53 psotfx Exp $
 *
 *
 ***************************************************************************/

/****************************************************************************
 * Traduzido por:
 * JuniorZ rs_junior@hotmail.com || http://usuarios.lycos.es/suportephpbb
 ****************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/

$faq[] = array("--","Informações sobre <i>Login</i> e <i>Registro</i>");
$faq[] = array("Porque é que não consigo <i>Logar</i> nos fóruns?", "Registrou-se? Você deve <u>Registrar</u>-se de forma a poder <u>Logar</u>. Foi expulso dos fóruns? Surgirá uma mensagem se tal aconteceu. Caso haja uma expulsão deve contactar o 'webmaster' ou o Administrador do fórum e perguntar o porquê caso não saiba a razão. Caso esteja registrado e não se encontre expulso e mesmo assim não consiga <u>Logar</u>, verifique novamente se o seu <u>Nome de Usuário</u> e <u>Senha</u> são os corretos. Normalmente é esse o problema. Caso não saiba mesmo o que se passa e não seja nenhuma das razões acima descritas contacte o Administrador do fórum porque poderá haver alguma configuração errada no sistema.");
$faq[] = array("Porque é que tenho que me <i>Registrar</i>?", "Poderá não ser necessário. Fica inteiramente ao critério do Administrador dos fóruns se é necessário o registro para postar mensagens. Contudo, o registro dá-lhe acesso a funções adicionais e possivelmente fóruns que não estão disponíveis a visitantes que se apresentam no anonimato. Alguns exemplos são o uso e definição de imagens <u>Avatar</u> , uso de <u><b>M</b>ensagens <b>P</b>rivadas</u>, enviar e receber <u>email</u> entre usuários, subscrição de <u>Grupos de Usuários</u>, etc. São necessários apenas alguns segundos para se fazer o registro, sendo assim é recomendável que o faça.");
$faq[] = array("Porque eu sou desconectado (deslogado) automaticamente do fórum?", "Se não assinalar <u>Permanecer Logado automaticamente em cada visita </u> antes de clicar em <u>Entrar</u>, o sistema não o reconhecerá da próxima vez que visitar o fórum. Isto evita o uso abusivo da sua conta por outra pessoa. Para se manter conectado e não necessitar de escrever o seu <u>Nome de Usuário</u> e <u>Senha</u> assinale essa caixa quando entrar no fórum. Tal procedimento não recomendável caso o acesso aos fóruns seja feito num computador compartilhado com outros usuários, ou seja, bibliotecas, cyber café, departamentos em universidade, etc.");
$faq[] = array("Como posso evitar que o meu <i>Nome</i> de <i>Usuário</i> apareça na lista de <i>Usuários Online</i>?", "No seu <u>Perfil</u> há uma opção <u>Ocultar meu status Online</u>. Se assinalar <u>Sim</u> apenas você e o Administrador poderão ver que se encontra online. Passará a ser tomado pelo sistema do phpBB 2 como um <u>Usuário Invisível</u>.");
$faq[] = array("Perdi a minha <i>Senha</i>!", "Não entre em pânico! Apesar da sua <u>Senha</u> não poder ser recuperada pela Administração do fórum pode no entanto ser feito como se nunca a tivesse registrado, ou seja, como se estivesse entrando pela primeira vez no fórum. Para fazer isto clique em <u>Entrar</u> e em seguida em <u>Esqueci-me da Senha</u>. Preencha os campos Usuário e Endereço de Email e em minutos você poderá ter acesso ao fórum");
$faq[] = array("Registrei-me mas não consigo <i>Logar</i>!", "Primeiro verifique se o <u>Nome de Usuário</u> e <u>Senha</u> estão corretos. Caso estejam corretos e mesmo assim não for possível entrar no fórum então uma entre duas coisas podem ter acontecido - se a função de COPPA encontra-se ativa nos fóruns e você tem menos de 13 anos de idade então terá que seguir as instruções para que a sua conta seja ativada. Se este não for o caso, será que o seu registro necessita ser ativado? Alguns administradores pretendem que o registro do seu novo usuário seja ativado através de um email, antes que possa efetivamente <u>Logar</u> nos fóruns. Caso isso aconteça, você será informado se o processo de ativação é necessário ou não. Se recebeu um email então siga as suas instruções. Se não recebeu o email, será que o endereço de email fornecido, durante o registro, é válido? Uma das razões para a ativação ser feita é para reduzir o número abusos do sistema por usuários <i>disfarçados</i> ou anônimos. Se tem certeza de que o endereço de email fornecido é válido e correto tente então contactar o Administrador do fórum.");
$faq[] = array("Registrei-me no passado mas não consigo mais <i>Logar</i>?!", "As razões mais prováveis são; escreveu <u>Nome de Usuário</u> ou <u>Senha</u> incorretos (verifique o email que lhe foi enviado), ou o administrador poderá ter removido o seu registro por algum motivo. É comum administradores removerem registros de usuários que nunca colocaram mensagens, de forma a reduzir o tamanho da base de dados. Tente registrar-se novamente e envolver-se nos assuntos dos fóruns.");


$faq[] = array("--","Preferências e Configuração de Usuários");
$faq[] = array("Como mudo a minha configuração?", "Toda a sua configuração (após o processo de <u>Registro</u>) é guardada na base de dados. Para alterá-la clique em <u>Perfil</u> (normalmente no topo das páginas, dependendo do estilo dos fóruns em uso). A partir daí pode alterar a sua configuração.");
$faq[] = array("As datas não são as corretas!", "As datas decerto estão corretas, contudo pode acontecer  de você estar vendo as horas em um fuso horário diferente de onde você se encontra. Se é esse o caso mude no seu <u>Perfil</u> a opção para o <u>Fuso Horário</u> de forma a abranger a sua área, ou seja, Brasil, Londres, Paris, ou onde se encontre. Note que a mudança do fuso horário bem como a maior parte das opções de perfil só é permitida a usuários registrados. Se ainda não é o seu caso chegou o momento certo para registrar-se!");
$faq[] = array("Mudei o <i>Fuso Horário</i> mas a hora continua errada!", "Se tem certeza de que o <u>Fuso Horário</u> que escolheu é o correto mas a hora não é a real, é possível que seja devido ao horário de Verão. O phpBB não se encontra desenhado para efetuar essas mudanças automaticamente, sendo assim elas devem ser ajustadas manualmente pelos usuários.");
$faq[] = array("A língua da minha nacionalidade não se encontra na lista!", "A razão mais provável é o Administrador não ter instalado essa língua ou o phpBB ainda não ter sido traduzido para a mesma. Peça ao Administrador que instale esse 'pacote de língua' e, caso não exista, você poderá criar uma nova tradução. Para mais informação consultar a página oficial do <b>Grupo phpBB</b> (seguir o atalho no rodapé destas páginas)");
$faq[] = array("Como posso mostrar uma imagem abaixo do meu <i>Nome de Usuário</i>?", "Deve haver duas imagens abaixo de cada Nome de Usuário em cada mensagem - a primeira representa o rank do usuário, que está relacionada ao número de mensagens enviados ao fórum e a outra, se existir, é uma imagem maior conhecida como Avatar, que é normalmente única ou pertencente a cada usuário. O Administrador dos fóruns decide se permite ou não o uso de <u>Avatares</u> bem como a maneira em que os usuários podem usá-las. Se você não consegue colocar o seu, então foi decisão do Administrador dos fóruns a proibição. Pergunte-lhe a razão (temos a certeza que existe uma boa justificativa!)");
$faq[] = array("Como posso mudar o meu <i>Rank</i>?", "De uma forma geral o usuário normal não pode alterar diretamente o seu rank (o rank aparece abaixo do Nome de Usuário em tópicos e no 'Perfil' dependendo do estilo do fórum em uso). O rank está relacionado ao número de mensagens que você colocou no fórum ou caracteriza usuários especiais como: moderadores e administradores. Por favor não abuse dos fóruns colocando mensagens desnecessárias apenas para aumentar o seu rank pois o Moderador ou Administrador poderão tomar alguma atitude contra, caso verifiquem que houve abuso.");
$faq[] = array("Quando clico no atalho de <i>Email</i> de um usuário aparece uma mensagem para <i>Logar</i>!", "Lamentamos mas apenas usuários registrados poderão enviar <u>email</u> a pessoas através do formulário exclusivo do fórum (caso o administrador tenha ativado esta função). Isso é para evitar o uso indevido do sistema de email por usuários anônimos.");


$faq[] = array("--","Questões na colocação de mensagens");
$faq[] = array("Como posso colocar uma mensagem num fórum?", "Fácil, clique no respectivo botão tanto no fórum como no tópico onde se encontre (dependendo do estilo de fórum em uso, normalmente os botões têm a designação de <u>Nova Mensagem</u>, <u>Novo Tópico</u> ou <u>Responder</u>). Talvez seja necessário o seu registro nos fóruns para poder postar mensagens. Existe uma lista de ações que lhe são permitidas, havendo registro ou não, na parte inferior do lado direito da página de cada fórum (<u>Pode colocar mensagens novas, Pode votar, etc.</u>)");
$faq[] = array("Como posso <i>editar</i> ou <i>remover</i> uma mensagem?", "A menos que seja um administrador de fórum você apenas pode <u>editar</u> ou <u>remover</u> as suas próprias mensagens. Para editar uma mensagem (por vezes apenas por um período limitado após ser colocada) clique no botão <u>editar</u> na parte superior desta mensagem (dependendo do estilo de fórum em uso). Caso alguém tenha já respondido esta mensagem você encontrará um pequeno texto ao fundo, mencionando que foi editada e eventualmente quantas vezes. Isto não aparece caso essa mensagem ainda não tenha respostas. Também não aparecerá se a alteração for feita por algum Administrador ou Moderador (possivelmente eles deixarão uma mensagem dizendo o que foi alterado e o motivo). Note que usuários normais não podem remover uma mensagem após alguém ter colocado uma resposta.");
$faq[] = array("Como adiciono uma <i>assinatura</i> a uma mensagem?", "Para adicionar uma assinatura a uma mensagem você deverá primeiro criar uma no seu <u>Perfil</u> no respectivo local. Uma vez criada você poderá configurar o fórum, também em <u>Perfil</u>, para <u>Sempre anexar minha assinatura</u> às mensagens ou colocá-la apenas quando assim o quiser, assinalando <u>Adicionar Assinatura</u> na lista de opções abaixo da caixa de escrita de cada mensagem.");
$faq[] = array("Como posso <i>adicionar uma enquete</i>?", "Criar uma enquete é fácil. Ao postar um tópico novo (ou editar a primeira mensagem de um tópico, caso tenha permissão para tal) você encontrará abaixo da caixa principal da mensagem um painel com o título <u>Adicionar Enquete</u> (se você não vê isto é porque provavelmente não possui permissão para criar enquetes ou o tópico não é de sua autoria). Deverá escrever um título para a enquete no local apropriado e em seguida colocar pelo menos duas <u>Opções de escolha</u> (para adicionar uma opção escreva o que pretende e clique no botão <u>Adicionar opção de escolha para a enquete</u>. Deverá também estipular um limite de tempo para a votação, sendo 0 uma enquete sem prazo para terminar. O número de opções de escolha é determinado e configurado pelo Administrador dos fóruns");
$faq[] = array("Como posso <i>editar</i> ou <i>remover</i> uma <i>enquete</i>?", "Da mesma forma que as mensagens as enquetes apenas poderão ser editadas pelo seu autor, um moderador ou o Administrador dos fóruns. Para editar uma enquete clique na primeira mensagem do tópico (esta mensagem é a que tem a votação associada ao tópico). Caso ninguém tenha votado os seus autores poderão remover a enquete ou editar as suas opções de escolha. Contudo, se os usuários já votaram apenas moderadores e administradores podem editar ou remover esta votação. Isto é para evitar que sejam alteradas as opções de escolha de enquetes em curso");
$faq[] = array("Porque não consigo entrar num fórum?", "O acesso a alguns fóruns poderá estar limitado apenas a determinados usuários ou grupos. Para verificar, ler, colocar mensagens, etc., você precisará de uma autorização especial. Apenas o moderador desse fórum e um Administrador podem permitir esse acesso. Contacte-os caso ache necessário.");
$faq[] = array("Porque não posso votar?", "Apenas usuários registrados podem submeter os seus votos (para impedir duplicação nos resultados). Caso você possua registro mas mesmo assim não consegue votar então possivelmente não lhe foi atribuida permissão para tal.");


$faq[] = array("--","Formatos e tipos de Tópicos");
$faq[] = array("O que é <i>BBCode</i>?", "BBCode é uma implementação especial de HTML. A liberação do uso do BBCode nos fóruns está a critério do Administrador. (caso lhe seja permitido pode controlar o seu uso em <u>Desativar BBCode nesta mensagem</u>). O BBCode por si mesmo é similar em estilo ao HTML, as tags são introduzidas entre colchetes [e] em vez de &lt; and &gt; e proporcionam um maior controle do que e como algo é apresentado. Para mais informações sobre o BBCode veja o respectivo guia, acessível na página das mensagens.");
$faq[] = array("Posso usar <i>HTML</i>?", "Depende se o Administrador permitir, ele tem o controle completo sobre isso. Se for permitido o uso de HTML provavelmente apenas alguns códigos serão acessíveis. Isto é uma medida de <i>segurança</i> para evitar que pessoas abusem do fórum usando códigos que possam destruir o seu formato ou causar outros problemas. Caso o HTML esteja ativo você pode desativá-lo em cada mensagem assinalando <u>Desativar HTML nesta mensagem</u>.");
$faq[] = array("O que são <i>Smileys</i>?", "Smileys ou Emoticons são pequenas representações gráficas que podem ser usadas para expressar algum sentimento usando poucos caracteres, ou seja, :) quer dizer feliz, :( quer dizer triste. Uma lista completa de <u>Emoções</u> pode ser vista no formulário junto à caixa de cada mensagem. Tente evitar o uso excessivo dos smileys já que podem tornar uma mensagem ilegível podendo o Administrador ou um moderador removê-los ou apagar a mensagem por completo");
$faq[] = array("Posso <i>inserir imagens</i>?", "As imagens podem aparecer nas suas mensagens. Contudo, não há no momento uma maneira de carregar imagens diretamente no phpBB. Como tal você terá que linkar a imagem armazenada num servidor publicamente acessível, ou seja, http://www.algum-site.com.br/minha-imagem.gif. Não pode linkar ao fórum imagens guardadas no seu próprio PC (a menos que esse possua um servidor publicamente acessível) nem imagens armazenadas sob mecanismos que requeiram autenticação, como por exemplo caixas de correio eletrônico de Hotmail ou Yahoo, páginas protegidas por senha, etc. Para mostrar a imagem pode usar tanto o BBCode [img] como o código apropriado de HTML (se ativo).");
$faq[] = array("O que são <i>Anúncios</i>?", "Os Anúncios contém normalmente informação importante e você deve lê-los logo que eles surjam. Os Anúncios são automaticamente colocados no topo de cada página do fórum em que são afixados. Fazer uso dessa função depende das permissões que lhe foram dadas, configuradas pelo Administrador.");
$faq[] = array("O que é um tópico <i>Fixo</i>?", "Tópicos Fixos aparecem abaixo dos anúncios nos fóruns e apenas na primeira página. São geralmente importantes e como tal devem ser lidos logo que possível. Da mesma forma que os Anúncios, as permissões para postar as mensagens Fixas ficam a critério do Adminsitrador dos fóruns.");
$faq[] = array("O que é um tópico <i>Bloqueado</i>?", "Os tópicos são Bloqueados pelo Moderador ou pelo Administrador dos fóruns. Quando um tópico é bloqueado não é mais permitido aos usuários colocarem respostas e/ou responderem a qualquer enquete deste fórum, pois esta é fechada automaticamente. Os tópicos podem ser bloqueados por várias razões.");


$faq[] = array("--","Níveis de Usuários e Grupos");
$faq[] = array("O que são <i>Administradores</i>?", "Administradores são pessoas com o nível máximo de controle sobre todos os aspectos dos fóruns. Podem controlar toda a operação dos fóruns, incluindo criar, editar ou remover fóruns, determinar permissões, expulsar usuários, criar grupos de usuários ou moderadores, etc. Eles possuem igualmente todos os poderes de moderador em todos os fóruns existentes.");
$faq[] = array("O que são <i>Moderadores</i>?", "Moderadores são usuários (ou grupos de usuários) cujo trabalho é supervisionar diariamente o funcionamento dos fóruns que lhes estejam designados. Eles têm o poder de editar ou remover mensagens, bloquear, desbloquear, mover, remover e subdividir tópicos nos fóruns onde são moderadores. Geralmente os moderadores fiscalizam mensagens que possam estar <i>fora ou alé do assunto em discussão</i> ou o uso de material abusivo ou ofensivo.");
$faq[] = array("O que são <i>Grupos de Usuários</i>?", "<u>Grupos de Usuários</u> são uma forma dos administradores dos fóruns agruparem usuários. Cada usuário pode pertencer a vários grupos (isto difere da maioria dos outros tipos de Quadros de Mensagens) e a cada grupo podem ser dados direitos de acesso individuais. Isto torna mais fácil aos administradores destinarem vários usuários como moderadores de um determinado fórum ou dar-lhes acesso a um fórum privado, etc.");
$faq[] = array("Como me associo a um <i>Grupo de Usuários</i>?", "Para se associar a um Grupo de Usuários clique no link Grupos no topo da página (dependendo do desenho de cada modelo do phpBB no fórum), podendo então ver todos os Grupos. Nem todos os Grupos possuem um <i>acesso aberto</i>, alguns são fechados e alguns poderão inclusive encontrar-se invisíveis. Se o Grupo se encontra aberto você poderá então solicitar que seja membro clicando no botão apropriado. O moderador do Grupo de Usuários necessita aprovar o seu pedido, podendo perguntar-lhe a razão do mesmo. Por favor, não insista perante um Moderador de Grupo caso o seu pedido seja recusado. Eles têm as usas razões.");
$faq[] = array("Como posso vir a ser um <i>Moderador</i> de Grupo?", "Os Grupos de Usuários são inicialmente criados pelo Administrador dos fóruns o qual também encarrega alguém de ser Moderador. Se está interessado em criar um Grupo de Usuários o seu primeiro ponto de contacto será portanto o Administrador dos Fóruns, ao qual deverá contactar com uma <b>M</b>ensagem <b>P</b>rivada.");


$faq[] = array("--","<b>M</b>ensagens <b>P</b>rivadas");
$faq[] = array("Não consigo enviar <i><b>M</b>ensagens <b>P</b>rivadas<i>!", "Há três razões para que tal coisa possa acontecer; você não está registrado nos fóruns e/ou não se encontra online, o Administrador desligou a troca de Mensagens Privadas para todos os fóruns ou você foi impedido de enviar mensagens por algum motivo. Se é este o último caso você deverá perguntar ao Administrador qual a razão, caso não a saiba.");
$faq[] = array("Recebo <i><b>M</b>ensagens <b>P</b>rivadas</i> indesejáveis!", "No futuro iremos adicionar a possibilidade da existência de uma lista de usuários a serem ignorados no sistema de Mensagens Privadas. Por enquanto, caso você continue a receber mensagens privadas não solicitadas a partir de alguém em particular, informe o Administrador, que poderá inviabilizar qualquer usuário de enviar Mensagens privadas.");
$faq[] = array("Recebi de alguém neste fórum mensagens de <i>email</i> com assuntos irrelevantes ou abusivos!", "Embora o sistema de email neste fórum possua funções de segurança que tentam detectar usuários que enviem esse tipo de mensagem lamentamos que tal tenha acontecido. Você deve comunicar o acontecido ao Administrador dos fóruns com uma cópia completa do email recebido, sendo muito importante que inclua os cabeçalhos (nesses encontram-se os detalhes do usuário que enviou o email). O Administrador poderá então agir de acordo com cada caso.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","Questões sobre o programa phpBB 2");
$faq[] = array("Quem escreveu o phpBB 2?", "Este software (na sua forma não modificada) é produzido e publicado por <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>, que também detém os direitos autorais. Está disponível sob a licensa 'GNU General Public Licence' e pode ser distribuído gratuitamente. Visite o site para maiores informações");
$faq[] = array("Porque não há a função X?", "Este software foi escrito e licenciado pelo phpBB Group. Se pensa que alguma função pode ser adicionada visite a nossa página oficial em phpbb.com e veja o que o Grupo phpBB pode dizer sobre o assunto. Por favor, não coloque mensagens com pedido de funções no fórum em phpbb.com, o Grupo usa o sourceforge para resolver solicitações como esta. Por favor, leia cuidadosamente este fórum para ver se alguma posição já foi por nós tomada em relação à função em questão.");
$faq[] = array("A quem eu devo contactar sobre questões abusivas e/ou legais relacionadas a este fórum?", "Você deverá contactar o Administrador dos fóruns. Se não conseguir saber quem é contacte então um dos moderadores perguntando a quem o assunto deve ser enviado. No caso de mesmo assim não obter resposta contacte o dono do domínio (faça uma 'verificação de whois'). Por favor, o phpBB Group não possui absolutamente nenhum controle e não pode de qualquer maneira ser responsável sobre quando, onde e por quem este fórum é usado. Não há razão em contactar o phpBB Group em relação a qualquer questão legal (interrupção e desistência, de responsabilidade, comentário difamatório, etc.) não diretamente relacionado com o 'site' phpbb.com. Caso envie algum email ao phpBB Group sobre o uso deste software por terceiros, você poderá receber uma resposta concisa ou não receber resposta alguma.");

//
// This ends the FAQ entries
//

?>