<?php
/***************************************************************************
 *                       lang_bbcode.php [portuguese_br]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id: lang_bbcode.php,v 1.1.2.3 2002/11/13 23:28:53 psotfx Exp $
 *
 *
 ***************************************************************************/

/****************************************************************************
 * Traduzido por:
 * JuniorZ rs_junior@hotmail.com || http://usuarios.lycos.es/suportephpbb
 ****************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/

$faq[] = array("--","Introdução");
$faq[] = array("O que é BBCode?", "BBCode é uma implementação especial de HTML. A possibilidade de uso do BBCode nas suas mensagens é determinada pelo Administrador dos fóruns. Adicionalmente, você pode poderá desligar o BBCode em cada mensagem selecionando <b>Desativar BBCode nesta mensagem</b> abaixo da caixa principal de cada mensagem. BBCode é similar em estilo ao HTML, as tags são incluídas em colchetes [e] em vez de &lt; e &gt; proporcionando um maior controle sobre o que mostrar e como mostrar. A tarefa de adicionar BBCode às suas mensagen é facilitada pelo uso de um painel colocado imediatamente acima à caixa principal das mensagens, dependendo do modelo de phpBB em uso, onde pode escolher e aplicar os vários itens de acordo com o código que pretenda aplicar.");

$faq[] = array("--","Formatos de Texto");
$faq[] = array("Como criar texto em negrito, itálico e sublinhado", "O BBCode inclui tags que lhe permitem mudar rapidamente o estilo básico do texto. Isto é possível das seguintes formas: <ul><li>Para tornar uma parte do texto em negrito incluí-la entre <b>[b][/b]</b>, ou seja, <b>[b]</b>Olá<b>[/b]</b> passará a ser <b>Olá</b></li><li> Para sublinhar use <b>[u][/u]</b>. Por exemplo: <b>[u]</b>Bom Dia<b>[/u]</b> passa a ser <u>Bom Dia</u></li><li> Para tornar o texo itálico use <b>[i][/i]</b>, ou seja, Isto é <b>[i]</b>Ótimo!<b>[/i]</b> resulta em: Isto é <i>Ótimo!</i></li></ul>");
$faq[] = array("Como mudar a cor ou o tamanho do texto", "Para alterar a cor ou o tamanho do texto devem ser usadas as seguintes tags. Ter em mente que a forma como aparecerá no monitor de cada visitante depende do 'browser' ou do sistema que use: <ul><li> A mudança da cor do texto é feita englobando-o em <b>[color=][/color]</b>. Tanto pode especificar o nome de uma cor conhecida (terá que ser em ingês) (por exemplo: red, blue, yellow, etc.) ou especificando o seu valor hexadecimal, ou seja, #FFFFFF, #000000. Por exemplo, para criar texto em vermelho poderá usar:<br/><br/><b>[color=red]</b>Olá!<b>[/color]</b><br/><br/>ou<br/><br/><b>[color=#FF0000]</b>Olá!<b>[/color]</b><br/><br/> Ambos resultarão em <span style=\"color:red\">Olá!</span></li><li> A mudança do tamanho do texto pode ser feita de uma forma similar, usando <b>[size=][/size]</b>. Esta tag está dependente do Modelo de phpBB que você está usando mas o formato recomendado é um valor numérico representando o tamanho do texto em pixels, começando em 1 (tão pequeno que praticamente não se vê) até 29 (enorme). Por exemplo:<br/><br/><b>[size=9]</b>PEQUENO<b>[/size]</b><br/><br/> normalmente surge como <span style=\"font-size:9px\">PEQUENO</span><br/><br/> enquanto que <br/><br/><b>[size=24]</b>ENORME!<b>[/size]</b><br/><br/>será <span style=\"font-size:24px\">ENORME!</span></li></ul>");
$faq[] = array("Posso combinar tags de formato?", "Sim, claro que pode. Por exemplo, para cativar a atenção de alguém poderá escrever:<br/><br/><b>[size=18][color=red][b]</b>OLHE PARA MIM!<b>[/b][/color][/size]</b><br/><br/> que irá aparecer como <span style=\"color:red;font-size:18px\"><b>OLHE PARA MIM!</b></span><br/><br/> No entanto, não recomendamos o uso de muito texto da forma que acabamos de descrever! Lembre-se de que depende do autor da mensagem assegurar que os códigos sejam colocados corretamente. Por exemplo, isto está incorrecto:<br/><br/><b>[b][u]</b> errado<b>[/b][/u]</b>");

$faq[] = array("--","Citar e produzir texto de largura fixa");
$faq[] = array("Citar texto em respostas", "Há duas formas de reproduzir texto previamente feito (normalmente uma réplica de uma mensagem anterior), com ou sem referência.<ul><li>Quando utiliza a função <b>Citar</b> para responder a uma mensagem no fórum, note que o texto dessa mensagem é adicionado ao corpo da messagem incluído num <b>[quote=\"\"][/quote]</b> bloco. Este método permite-lhe citar com uma referência a uma pessoa ou o que você decidir colocar! Por exemplo, para citar uma peça de texto que o Sr. Silva escreveu, você escreverá:<br/><br/><b>[quote=\"Sr. Silva\"]</b>O texto que o Sr. Silva escreveu irá aqui<b>[/quote]</b><br/><br/> No resultado será adicionado automaticamente, <b>Sr. Silva escreveu:</b> antes do texto citado. Note que você <b>tem que</b> incluir aspas \"\" em volta do nome citado.</li><li>O segundo método permite-lhe citar algo sem referência a alguém ou algo. Para fazê-lo englobe o texto em tags <b>[quote][/quote]</b>. Quando verificar a mensagem verá que simplesmente surge, <b>Citação:</b> antes do texto.</li></ul>");
$faq[] = array("Produzir código ou texto com uma largura fixa", "Caso pretenda reproduzir uma porção de código ou de fato algo que requeira uma largura fixa, ou seja, tipo de fonte Courier, englobe o texto com as tags <b>[code][/code]</b>, como por exemplo<br/><br/><b>[code]</b>echo \"Isto é algum código\";<b>[/code]</b><br/><br/>O formato usado entre as tags <b>[code][/code]</b> é preservado quando posteriormente o verificar.");

$faq[] = array("--","Gerar listas");
$faq[] = array("Criar uma lista sem ordem específica", "O BBCode aceita dois tipos de listas, sem ordem e ordenada. São basicamente o mesmo que em HTML. Uma lista sem ordem produz cada item de uma forma seqüencial, um seguido ao outro, precedendo-o com um caracter. Para criar uma lista não-ordenada use <b>[list][/list]</b> e coloque cada item entre essas tags, usando <b>[*]</b> antes de cada um. Por exemplo, para listar as suas cores favoritas, escreva:<br/><br/><b>[list]</b><br/><b>[*]</b>Vermelho<br/><b>[*]</b>Azul<br/><b>[*]</b>Amarelo<br/><b>[/list]</b><br/><br/> Isto irá aparecer como:<ul><li>Vermelho</li><li>Azul</li><li>Amarelo</li></ul>");
$faq[] = array("Criar uma lista ordenada", "O segundo tipo de listas, a ordenada, proporciona-lhe controle do que vai aparecer antes de cada item. Para criar uma lista ordenada você usará <b>[list=1][/list]</b> de forma a criar uma lista numérica ou, <b>[list=a][/list]</b>, para uma lista alfabética. Da mesma forma que para o tipo de lista sem ordem os itens são precedidos de <b>[*]</b>. Por exemplo:<br/><br/><b>[list=1]</b><br/><b>[*]</b>Ir às compras<br/><b>[*]</b>Comprar um computador novo<br/><b>[*]</b>Insultar o computador quando trava<br/><b>[/list]</b><br/><br/>produzirá o seguinte:<ol type=\"1\"><li>Ir às compras</li><li>Comprar um computador novo</li><li>Insultar o computador quando trava</li></ol> Enquanto que para uma lista alfabética você usará:<br/><br/><b>[list=a]</b><br/><b>[*]</b>A primeira resposta<br/><b>[*]</b>A segunda resposta<br/><b>[*]</b>A terceira resposta<br/><b>[/list]</b><br/><br/>resultando em <ol type=\"a\"><li>A primeira resposta</li><li>A segunda resposta</li><li>A terceira resposta</li></ol>");

$faq[] = array("--", "Criar atalhos");
$faq[] = array("Criar um atalho para outra página ou site", "O phpBB BBCode aceita um número variável de formas para criar URIs, Uniform Resource Indicators, melhor conhecidos como URLs.<ul><li>A primeira dessas formas é usando a tag <b>[url=][/url]</b>. O que quer que escreva depois do sinal = faz com que o conteúdo desta tag aja como uma URL. Por exemplo, para fazer um atalho para a página phpBB.com escreva:<br/><br/><b>[url=http://www.phpbb.com/]</b>Visite phpBB!<b>[/url]</b><br/><br/> Isto irá resultar no seguinte atalho: <a href=\"http://www.phpbb.com/\" target=\"_blank\">Visite phpBB!</a>. Veja que a página irá abrir numa janela nova de forma a que o usuário possa continuar nos fóruns.</li><li> Se pretende que o URL esteja à vista, faça simplesmente isto:<br/><br/><b>[url]</b>http://www.phpbb.com/<b>[/url]</b><br/><br/>Tal resultará no seguinte atalho: <a href=\"http://www.phpbb.com/\" target=\"_blank\">http://www.phpbb.com/</a></li><li> Adicionalmente o phpBB possui algo chamado <i>Atalhos Mágicos</i>, função que permite transformar automaticamente qualquer URL escrita com um sintaxe correta num atalho sem ser necessário especificar quaisquer tags ou mesmo o prefixo http://. Por exemplo, escrevendo www.phpbb.com na sua mensagem, automaticamente resultará em <a href=\"http://www.phpbb.com/\" target=\"_blank\">www.phpbb.com</a> quando vir essa mensagem.</li><li> A mesma coisa se aplica aos endereços de email, podendo especificar o endereço. Por exemplo:<br/><br/><b>[email]</b>fulano@dominio.com.br<b>[/email]</b><br/><br/>que resultará em <a href=\"emailto:fulano@dominio.com.br\">fulano@dominio.com.br</a>, ou pode apenas escrever fulano@dominio.com.br na sua mensagem que será automaticamente convertida em atalho quando a mensagem for guardada.</li></ul>
Como em todos os códigos BBCode aqui apresentados pode misturar URLs com quaisquer outras tags. Como por exemplo, <b>[img][/img]</b> (ver o item seguinte), <b>[b][/b]</b>, etc. Em relação ao formato das tags está totalmente dependente do usuário assegurar a ordem correta de início e fim, por exemplo:<br/><br/><b>[url=http://www.phpbb.com/][img]</b>http://www.phpbb.com/images/phplogo.gif<b>[/url][/img]</b><br/><br/><u>não é</u> correto, o que pode levar à remoção da sua mensagem por algum moderador ou Administrador. Sendo assim tenha cuidado.");

$faq[] = array("--", "Mostrar imagens em mensagens");
$faq[] = array("Adicionar uma imagem a uma mensagem", "O BBCode incorpora uma tag para incluir imagens nas suas mensagens. Dois fatores muito importantes devem ser observados ao usar estas tags: a maioria dos usuários não gosta de ver muitas imagens em mensagens; segundo, a imagem que pretende mostrar deve existir na internet (por exemplo, não pode existir apenas no seu computador a menos que ele seja um servidor de páginas, esteja sempre ativo e seja publicamente acessível!). Não há no momento qualquer forma de armazenar imagens localmente com o phpBB (daremos especial atenção a esse assunto na próxima versão do phpBB). Para mostrar uma imagem você terá que envolver a URL da imagem com as tags <b>[img][/img]</b>. Por exemplo:<br/><br/><b>[img]</b>http://www.phpbb.com/images/phplogo.gif<b>[/img]</b><br/><br/> Como deve ter notado na seção da URL acima você pode englobar uma imagem numa tag <b>[url][/url]</b> se assim o desejar, ou seja, <br/><br/><b>[url=http://www.phpbb.com/][img]</b>http://www.phpbb.com/images/phplogo.gif<b>[/img][/url]</b><br/><br/>irá produzir:<br/><br/><a href=\"http://www.phpbb.com/\" target=\"_blank\"><img src=\"templates/subSilver/images/logo_phpBB_med.gif\" border=\"0\" alt=\"\" /></a><br/>");

$faq[] = array("--", "Outros assuntos");
$faq[] = array("Posso adicionar as minhas próprias tags?", "Não, receio que não possa ser feito diretamente no phpBB 2.0. Pensamos proporcionar, na próxima versão do phpBB, tags configuráveis do BBCode.");

//
// This ends the BBCode guide entries
//

?>