vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|07 Mar 2003 18:27:00 -0000
vti_extenderversion:SR|4.0.2.8912
vti_filesize:IR|20937
vti_backlinkinfo:VX|bianquini/cleintes(reserva\\ com\\ imagem)/baixo.asp bianquini/cleintes(reserva\\ com\\ imagem)/compra.asp bianquini/cleintes(reserva\\ com\\ imagem)/produtos.asp bianquini/cleintes(reserva\\ com\\ imagem)/sessoes.asp
vti_cacheddtm:TX|07 Mar 2003 18:27:00 -0000
vti_cachedlinkinfo:VX|H|default.asp H|default.asp H|default.asp H|sessoes.asp H|javascript:\\ history.back() A|comprar.asp S|produtos/<%=rs("impeq")%> H|produtos.asp S|<%=dirlingua%>/imagens/detalhes.gif A|comprar.asp S|produtos/<%=rs3("impeq")%> H|produtos.asp S|<%=dirlingua%>/imagens/detalhes.gif H|sessoes.asp H|sessoes.asp H|sessoes.asp H|sessoes.asp H|javascript:\\ history.back() A|comprar.asp S|produtos/<%=rs("impeq")%> H|produtos.asp S|<%=dirlingua%>/imagens/detalhes.gif A|comprar.asp S|produtos/<%=rs("impeq")%> H|produtos.asp S|<%=dirlingua%>/imagens/detalhes.gif H|javascript:\\ history.back()
vti_cachedsvcrellinks:VX|FHUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/default.asp FHUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/default.asp FHUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/default.asp FHUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/sessoes.asp SHUS|javascript:\\ history.back() FAUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/comprar.asp USUS|produtos/<%=rs("impeq")%> FHUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/produtos.asp USUS|<%=dirlingua%>/imagens/detalhes.gif FAUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/comprar.asp USUS|produtos/<%=rs3("impeq")%> FHUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/produtos.asp USUS|<%=dirlingua%>/imagens/detalhes.gif FHUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/sessoes.asp FHUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/sessoes.asp FHUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/sessoes.asp FHUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/sessoes.asp SHUS|javascript:\\ history.back() FAUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/comprar.asp USUS|produtos/<%=rs("impeq")%> FHUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/produtos.asp USUS|<%=dirlingua%>/imagens/detalhes.gif FAUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/comprar.asp USUS|produtos/<%=rs("impeq")%> FHUS|bianquini/cleintes(RESERVA\\ COM\\ IMAGEM)/produtos.asp USUS|<%=dirlingua%>/imagens/detalhes.gif SHUS|javascript:\\ history.back()
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
